### ISSUE TITLE
Can't use Scala 2.12.10 along with --jvm 8

### ISSUE THREAD

**Issue by alexarchambault** [VirtusLab/scala-cli#1092]
Currently happening with Scala CLI `0.1.7`.

```text
$ echo 'println("Hello")' | scala-cli - -S 2.12.10 --jvm 8
Compiling project (Scala 2.12.10, JVM)
Error compiling project (Scala 2.12.10, JVM)
Error: Unexpected error when compiling project_47559e4706_47559e4706: 'null'
Compilation failed
```

`scala-cli bloop output` doesn't provide anything meaningful, but I suspect it's not working correctly. When running `scala-cli bloop exit`, then running the command above in verbose mode, we get the following stacktrace from Bloop:
```text
java.nio.file.ClosedFileSystemException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.ensureOpen(ZipFileSystem.java:1619)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.getFileAttributes(ZipFileSystem.java:531)
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.readAttributes(ZipPath.java:767)
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.readAttributes(ZipPath.java:777)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:276)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.nio.file.Files.size(Files.java:2468)
	at sbt.internal.inc.HashUtil$.farmHash(HashUtil.scala:31)
	at sbt.internal.inc.FarmHash$.ofPath(Stamp.scala:89)
	at sbt.internal.inc.Stamper$.$anonfun$forHashInRootPaths$3(Stamp.scala:233)
	at sbt.internal.inc.Stamper$.tryStamp(Stamp.scala:188)
	at sbt.internal.inc.Stamper$.$anonfun$forHashInRootPaths$1(Stamp.scala:233)
	at sbt.internal.inc.UncachedStamps.library(Stamp.scala:465)
	at sbt.internal.inc.InitialStamps.$anonfun$library$1(Stamp.scala:419)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
	at sbt.internal.inc.InitialStamps.library(Stamp.scala:419)
	at sbt.internal.inc.bloop.internal.BloopAnalysisCallback.$anonfun$addProductsAndDeps$16(BloopAnalysisCallback.scala:409)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.mutable.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:50)
	at scala.collection.SetLike.map(SetLike.scala:105)
	at scala.collection.SetLike.map$(SetLike.scala:105)
	at scala.collection.mutable.AbstractSet.map(Set.scala:50)
	at sbt.internal.inc.bloop.internal.BloopAnalysisCallback.$anonfun$addProductsAndDeps$1(BloopAnalysisCallback.scala:400)
	at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
	at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:108)
	at sbt.internal.inc.bloop.internal.BloopAnalysisCallback.addProductsAndDeps(BloopAnalysisCallback.scala:358)
	at sbt.internal.inc.bloop.internal.BloopAnalysisCallback.get(BloopAnalysisCallback.scala:300)
	at sbt.internal.inc.bloop.internal.BloopIncremental$.$anonfun$compileIncremental$5(BloopIncremental.scala:119)
	at monix.eval.Task.$anonfun$map$1(Task.scala:407)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:176)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

A bit of debugging shows that it's thrown by the `library` call [here](https://github.com/scala-cli/bloop-core/blob/cbbe37ca36088fe314844bae5e8bf8ebbaf89060/backend/src/main/scala/sbt/internal/inc/bloop/internal/BloopAnalysisCallback.scala#L400), while `virtual.toString` is `/8/java.base/java/lang/String.sig`.

**Comment by alexarchambault** [comment]
Things work fine when bumping to `2.12.15`, or to Java `17`. But I'm wondering if we could handle this better (maybe warn users if we detect incompatible Scala and JVM versions, and also have Bloop report the exception above through BSP).

**Comment by alexarchambault** [comment]
Might be worth reporting to Bloop actually…

**Comment by alexarchambault** [comment]
Fixed by https://github.com/VirtusLab/scala-cli/pull/1257 / https://github.com/scala-cli/bloop-core/pull/112.
