### ISSUE TITLE
Cannot run java file when scala version is set

### ISSUE THREAD

**Issue by tpasternak** [VirtusLab/scala-cli#1211]
**Version(s)**
0.1.10

**Describe the bug**
Try to run this file with `scala-cli -S 2 Main.java`
```
class Main {
    public static void main(String[] args) {

    }
}
```

**Expected behaviour**
Program runs without error

**Actual behaviour**
```
Exception in thread "main" java.lang.IllegalAccessException: class scala.cli.runner.Runner$ cannot access a member of class Main with modifiers "public static"
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Method.invoke(Method.java:558)
	at scala.cli.runner.Runner$.main(Runner.scala:15)
	at scala.cli.runner.Runner.main(Runner.scala)
```

**Comment by MaciejG604** [comment]
The above example does work with Scala CLI 1.0.4
