### ISSUE TITLE
Bloop connection failure in github actions?

### ISSUE THREAD

**Issue by Quafadas** [VirtusLab/scala-cli#1797]
**Version(s)**
0.1.20 (inside github actions)

**Describe the bug**
I've been attempting to add scala support to the [quicktype](https://github.com/quicktype/quicktype) project.

I've reached the stage, where I get the tests to pass locally. However, they fail in CI. The reason would _appear_ to be that scala-cli is struggling to maintain / create it's connection to bloop. 

@lwronski has kindly provided an initial investigation. His fork of my fork on the scala3 branch illustrates the issues, with diagnostic flags enabled. I believe this github action log to be the right place to look for diagnostic information.
https://github.com/lwronski/quicktype/actions/runs/3957852464/jobs/6778729315#step:6:945

I'm happy to provide more help if I can if that is not the right starting point.

**To Reproduce**
Trigger CI on the scala3 branch of the fork above. 

**Expected behaviour**
The scala3 test command passes for me locally. My aim is to have it pass in CI. That goal is (obviously) outside the scope of this report, but I _believe_ would be the outcome, should scala cli maintain it's connection to bloop. My understanding of the actual issue itself is superficial enough, that I cannot provide a significantly better goal.

**Comment by Quafadas** [comment]
In case it helps, this is the entrypoint for the tests; 
https://github.com/lwronski/quicktype/blob/scala3/test/fixtures/scala3/run.sh

Locally, one should be able to trigger the suite via; 
`FIXTURE=scala3 npm test`

A final point which has just now occured to me, is that my understanding of the way this works, is that there is some "superscript" copying the scala3 directory, changing it's inputs and then calling run.sh, many times and in parrallel from different copied directories. This implies that many scala-cli's would be trying to run at the same time. I'm unclear if that is problematic.

**Comment by alexarchambault** [comment]
It seems the error originates from our Bloop server not re-attempting to start or check if a server is already running, around [here](https://github.com/scala-cli/bloop-core/blob/1e0724764a0cca2b16520bb3675a61e42aa07c2e/frontend/src/main/scala/bloop/Bloop.scala#L88-L93). https://github.com/scala-cli/bloop-core/pull/128 ought to fix that.

**Comment by Quafadas** [comment]
Wow... that was quick - cool... I'll be getting excited about the next release :-)!

**Comment by lwronski** [comment]
~~I tested it with the nightly version of `scala-cli` and now I have the new following [error](https://github.com/lwronski/quicktype/actions/runs/3974922766/jobs/6814473300#step:6:874):~~

```
Exception in thread "main" java.nio.file.FileAlreadyExistsException: /home/runner/.cache/scalacli/local-repo/.v0.1.20-7-f4528d.tmp/org.virtuslab.scala-cli/runner_3/0.1.20-7-gf4528d92-SNAPSHOT/jars/runner_3.jar
	at java.base@17.0.5/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base@17.0.5/java.nio.file.Files.newByteChannel(Files.java:380)
	at os.write$.write(ReadWriteOps.scala:59)
	at os.write$.apply(ReadWriteOps.scala:70)
	at scala.build.LocalRepo$.extractZip(LocalRepo.scala:38)
	at scala.build.LocalRepo$.localRepo$$anonfun$1$$anonfun$2$$anonfun$2(LocalRepo.scala:84)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.build.LocalRepo$.using(LocalRepo.scala:23)
	at scala.build.LocalRepo$.localRepo$$anonfun$1$$anonfun$2(LocalRepo.scala:84)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.build.LocalRepo$.using(LocalRepo.scala:23)
	at scala.build.LocalRepo$.localRepo$$anonfun$1(LocalRepo.scala:85)
	at scala.build.LocalRepo$.localRepo$$anonfun$adapted$1(LocalRepo.scala:88)
	at scala.build.LocalRepo$.withLock(LocalRepo.scala:114)
	at scala.build.LocalRepo$.localRepo(LocalRepo.scala:88)
	at scala.cli.commands.shared.SharedOptions.buildOptions$$anonfun$1(SharedOptions.scala:336)
	at scala.build.EitherCps$Helper.apply(EitherCps.scala:19)
	at scala.cli.commands.shared.SharedOptions.buildOptions(SharedOptions.scala:350)
	at scala.cli.commands.ScalaCommand.buildOptions$$anonfun$1(ScalaCommand.scala:246)
	at scala.Option.map(Option.scala:242)
	at scala.cli.commands.ScalaCommand.buildOptions(ScalaCommand.scala:246)
	at scala.cli.commands.ScalaCommand.run(ScalaCommand.scala:269)
	at scala.cli.commands.ScalaCommand.run(ScalaCommand.scala:266)
	at caseapp.core.app.CaseApp.main(CaseApp.scala:150)
	at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:120)
	at scala.cli.ScalaCliCommands.main(ScalaCliCommands.scala:125)
	at scala.cli.ScalaCli$.main0(ScalaCli.scala:198)
	at scala.cli.ScalaCli$.main(ScalaCli.scala:102)
	at scala.cli.ScalaCli.main(ScalaCli.scala)
```

~~I run the following commands:~~
```
wget wget https://github.com/VirtusLab/scala-cli/releases/download/nightly/scala-cli-x86_64-pc-linux.gz
gunzip scala-cli-x86_64-pc-linux.gz
chmod +x scala-cli-x86_64-pc-linux 
./scala-cli-x86_64-pc-linux  -v -v -v circe.scala TopLevel.scala 
```

**Comment by lwronski** [comment]
@Quafadas It looks like I should use the static `scala-cli` launcher for testing purposes. If you download `scala-cli` like this, it should work:
```
wget https://github.com/VirtusLab/scala-cli/releases/download/nightly/scala-cli-x86_64-pc-linux-static.gz
gunzip scala-cli-x86_64-pc-linux-static.gz
chmod +x scala-cli-x86_64-pc-linux-static
./scala-cli-x86_64-pc-linux-static  -v -v -v circe.scala TopLevel.scala 
```

Can you test it if it works for you?

**Comment by Quafadas** [comment]
@lwronski Sorry for the delay, I had a bit of a git malfunction. 

The outcome looks a little funny. This does seem to run the tests successfully, but not then complete the job... 

I'm happy to wait for the release and take it on faith that this is some blip that won't occur "in real"?

**Comment by lwronski** [comment]
@Quafadas Thanks, I investigated this more and I have the following observation. If I add this step `run: echo '@main def hello() = println("Hello")' | scala-cli _` into `test-pr.yaml`:

```
            - name: Install scala
              if: ${{ contains(matrix.fixture, 'scala3') }}
              uses: VirtusLab/scala-cli-setup@main
            - run: echo '@main def hello() = println("Hello")' | scala-cli _
              if: ${{ contains(matrix.fixture, 'scala3') }}
            - run: QUICKTEST=true FIXTURE=${{ matrix.fixture }} npm test
```
It works on CI. I forked `QuickType` repo and run CI in my fork - [here](https://github.com/lwronski/quicktype/actions/runs/4015980810/jobs/6898402205) you can find job.

And locally I am only able to reproduce the error you see on CI if I run `bloop exit` before running the test:
```
scala-cli bloop exit
```

So my suspicion is that the command `FIXTURE=scala3 npm test` expects that all processes that are running by the script `test/fixtures/scala3/run.sh` will finish, but that `scala-cli` starts a bloop which is a server so it never ends. That's why on CI you observe that the job never ends.

**Comment by lwronski** [comment]
I confirm my suspicion, when I killed bloop process, the execution of this command ends - `FIXTURE=scala3 npm test`.

**Comment by Quafadas** [comment]
Thanks so much for all your help. 

Closing as definitely seems to work in the latest release :-).
https://github.com/quicktype/quicktype/actions/runs/4306899769/jobs/7511311857
