### ISSUE TITLE
Non-deterministic inability to connect to bloop at times

### ISSUE THREAD

**Issue by anatoliykmetyuk** [VirtusLab/scala-cli#180]
I have a Scala script that I run regularly, and at times, it fails with:

```
Exception in thread "main" java.io.IOException: Can't connect to 127.0.0.1:49442
        at scala.build.bloop.BloopServer$.create$1(BloopServer.scala:89)
        at scala.build.bloop.BloopServer$.connect(BloopServer.scala:97)
        at scala.build.bloop.BloopServer$.bsp(BloopServer.scala:120) 
        at scala.build.bloop.BloopServer$.buildServer(BloopServer.scala:138)
        at scala.build.bloop.BloopServer$.withBuildServer(BloopServer.scala:203)
        at scala.build.Build$.build(Build.scala:190)
        at scala.build.Build$.build(Build.scala:207)        
        at scala.cli.commands.Run$.run(Run.scala:52)                            
        at scala.cli.commands.DefaultBase.run(DefaultBase.scala:25)
        at scala.cli.commands.DefaultBase.run(DefaultBase.scala:5)
        at caseapp.core.app.CaseApp.main(CaseApp.scala:150)
        at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:112)
        at scala.cli.ScalaCli$.main(ScalaCli.scala:61)
        at scala.cli.ScalaCli.main(ScalaCli.scala)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_net_ConnectException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:609)
        at java.net.Socket.connect(Socket.java:558)
        at java.net.Socket.<init>(Socket.java:454)
        at java.net.Socket.<init>(Socket.java:231)
        at scala.build.blooprifle.internal.Operations$$anon$2.openSocket(Operations.scala:205)
        at scala.build.blooprifle.BloopRifle$$anon$2.openSocket(BloopRifle.scala:118)
        at scala.build.bloop.BloopServer$.create$1(BloopServer.scala:81)
        ... 13 more
```

I haven't found what causes the problem, nor did I find how to fix it...

**Comment by anatoliykmetyuk** [comment]
This could be caused by me updating Mac to Big Sur and they strictening the rules to connect to local ports. Just a guess. However I don't know how to lift those rules.

**Comment by tpasternak** [comment]
Hey @anatoliykmetyuk , thank you for reporting this. Which version of scala-cli you are using?

**Comment by anatoliykmetyuk** [comment]
`Scala CLI version 0.0.1+7-g76d17af-SNAPSHOT (v0.0.1-7-76d17a)`

**Comment by tpasternak** [comment]
@alexarchambault do you think this could be fixed in new Bloop?

**Comment by alexarchambault** [comment]
I'm not sure what causes the issue @anatoliykmetyuk is seeing.

But many things changed since 76d17af. We now default to domain sockets for the BSP connection in particular. And we also restart Bloop if its version is too old.

**Comment by romanowski** [comment]
@anatoliykmetyuk I am closing the issue now since it was using quite an ancient version of Scala CLI. In case you see similar problems with current versions, please open another issue.
