### ISSUE TITLE
Compile comand hangs

### ISSUE THREAD

**Issue by mbesida** [VirtusLab/scala-cli#1905]
**Version(s)**
Tested on 0.2.0

**Describe the bug**
scala-cli `compile` command hangs for this program
```scala
//> using scala "3.2.2"
//> using dep "co.fs2::fs2-io:3.6.1"

import cats.effect.*
import fs2.*

object Main extends IOApp.Simple:
  def run: IO[Unit] = Stream.duration
```

**To Reproduce**
Run `scala-cli compile .` of the program mentioned above

**Expected behaviour**
I expect this program to fail compilation, but scala-cli just hangs(leaving bloop process hanging as well)
Interestingly, when I comment out `Stream.duration` part compilation succeeds `def run: IO[Unit] = ???//Stream.duration`
So this happens when `Stream.duration` is present in the code

Also could be somehow related with this bug https://github.com/VirtusLab/scala-cli/issues/532, but in my case I have scala program(not a script) with explicit main method

**Comment by SethTisue** [comment]
If I bypass scala-cli and invoke the compiler directly with:

```
% /usr/local/scala/scala3-3.2.2/bin/scalac -classpath \
  `cs fetch --classpath co.fs2::fs2-io:3.6.1` \
  S.scala 
```

then I get

```
java.lang.OutOfMemoryError: Java heap space while typechecking S.scala
java.lang.OutOfMemoryError: Java heap space while compiling S.scala
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at dotty.tools.dotc.util.WeakHashSet.resize(WeakHashSet.scala:114)
	at dotty.tools.dotc.util.WeakHashSet.addEntryAt(WeakHashSet.scala:161)
	at dotty.tools.dotc.core.Uniques$NamedTypeUniques.linkedListLoop$1(Uniques.scala:56)
...
```

and with 3.3.0-RC3 instead of 3.2.2, same

so this would need to be reported over at https://github.com/lampepfl/dotty/issues

not sure why hang vs. OOME, but perhaps that's because of different JVM settings such as heap size

**Comment by lwronski** [comment]
I think this issue may be related to #1781, where bloop doesn't properly handle `java.lang.OutOfMemoryError` from compiler.

When I tried to run this example with `--server=false`, it seemed to work, but I had to wait a while to get a result:

```
➜  scala-demo scala-cli Hello.scala --server=false
-- Error: /private/tmp/scala-demo/Hello.scala:8:37 -----------------------------
8 |  def run: IO[Unit] = Stream.duration
  |                                     ^
  |No given instance of type cats.effect.kernel.Clock[F] was found for parameter F of method duration in object Stream
  |
  |where:    F is a type variable with constraint <: [_] =>> Any
  |.
  |I found:
  |
  |    cats.effect.kernel.Clock.clockForOptionT[F](
  |      /* ambiguous: both method catsInstancesForTry in object Invariant and method catsInstancesForQueue in object Invariant match type cats.Monad[F] */
  |        summon[cats.Monad[F]]
  |    , 
  |      cats.effect.kernel.Clock.clockForStateT[F, S](
  |        /* ambiguous: both method catsInstancesForTry in object Invariant and method catsInstancesForQueue in object Invariant match type cats.Monad[F] */
  |          summon[cats.Monad[F]]
  |      , 
  |        cats.effect.kernel.Clock.clockForEitherT[F, E](
  |          /* ambiguous: both method catsInstancesForTry in object Invariant and method catsInstancesForQueue in object Invariant match type cats.Monad[F] */
  |            summon[cats.Monad[F]]
  |        , 
  |          cats.effect.kernel.Clock.clockForKleisli[F, R](
  |            /* ambiguous: both method catsInstancesForTry in object Invariant and method catsInstancesForQueue in object Invariant match type cats.Monad[F] */
  |              summon[cats.Monad[F]]
  |          , 
  |            cats.effect.kernel.Clock.clockForWriterT[F, L](
  |              /* ambiguous: both method catsInstancesForTry in object Invariant and method catsInstancesForQueue in object Invariant match type cats.Monad[F] */
  |                summon[cats.Monad[F]]
  |            , 
  |              cats.effect.kernel.Clock.clockForIorT[F, L](
  |                /* ambiguous: both method catsInstancesForTry in object Invariant and method catsInstancesForQueue in object Invariant match type cats.Monad[F] */
  |                  summon[cats.Monad[F]]
  |              , 
  |                cats.effect.kernel.Clock.clockForContT[F, R](
  |                  /* ambiguous: both method catsInstancesForTry in object Invariant and method catsInstancesForQueue in object Invariant match type cats.Monad[F] */
  |                    summon[cats.Monad[F]]
  |                , 
  |                  cats.effect.kernel.Clock.clockForReaderWriterStateT[F, R, L, S](
  |                    /* ambiguous: both method catsInstancesForTry in object Invariant and method catsInstancesForQueue in object Invariant match type cats.Monad[F] */
  |                      summon[cats.Monad[F]]
  |                  , /* missing */summon[cats.effect.kernel.Clock[F]], ???)
  |                , ???)
  |              , ???)
  |            , ???)
  |          )
  |        )
  |      )
  |    )
  |
  |But no implicit values were found that match type cats.effect.kernel.Clock[F].
1 error found
Compilation failed
```

**Comment by lwronski** [comment]
I have checked this issue more deeply and have determined that #1781 don't address the problem reported in this issue. While #1781 dealt with `StackOverflowError`, but this issue is caused by a different exception - `java.lang.OutOfMemoryError`.

**Comment by tgodzik** [comment]
Looks like there is no way actually for us to report out of memory errors from Bloop, so the only option to check this is using server=false
