### ISSUE TITLE
Improve error message when user makes an error in ivy import

### ISSUE THREAD

**Issue by MarcinAman** [VirtusLab/scala-cli#192]
It would be nice to display something more meaningful when user makes an error in ivy imports.

To reproduce take a file and run scala-cli test on it:
```scala
import $ivy"com.novocode:junit-interface:0.11"
import org.junit.Test
import org.junit.Assert.*

class Test1:
  @Test def t1(): Unit = 
    assertEquals("I was compiled by Scala 3. :)", msg)
```

Error will be more or less:
```
maman@Marcins-MacBook-Pro ~/Documents/scala-cli (setup-ide-before-all) [1]> ./mill -i scala test ../example/scala3 -S 3.0.1                      (base) 
[132/506] de.tobiasroeser.mill.vcs.version.VcsVersion.vcsState 
[246/506] stubs.publishLocalNoFluff 
Publishing Artifact(org.virtuslab.scala-cli,stubs,0.0.4-SNAPSHOT) to ivy repo /Users/maman/Documents/scala-cli/out/repo/0.0.4-SNAPSHOT
[294/506] runner[2.13.6].publishLocalNoFluff 
Publishing Artifact(org.virtuslab.scala-cli,runner_2.13,0.0.4-SNAPSHOT) to ivy repo /Users/maman/Documents/scala-cli/out/repo/0.0.4-SNAPSHOT
[342/506] test-runner[2.13.6].publishLocalNoFluff 
Publishing Artifact(org.virtuslab.scala-cli,test-runner_2.13,0.0.4-SNAPSHOT) to ivy repo /Users/maman/Documents/scala-cli/out/repo/0.0.4-SNAPSHOT
[386/506] runner[2.12.15].publishLocalNoFluff 
Publishing Artifact(org.virtuslab.scala-cli,runner_2.12,0.0.4-SNAPSHOT) to ivy repo /Users/maman/Documents/scala-cli/out/repo/0.0.4-SNAPSHOT
[399/506] test-runner[2.12.15].publishLocalNoFluff 
Publishing Artifact(org.virtuslab.scala-cli,test-runner_2.12,0.0.4-SNAPSHOT) to ivy repo /Users/maman/Documents/scala-cli/out/repo/0.0.4-SNAPSHOT
[447/506] runner[3.0.2].publishLocalNoFluff 
Publishing Artifact(org.virtuslab.scala-cli,runner_3,0.0.4-SNAPSHOT) to ivy repo /Users/maman/Documents/scala-cli/out/repo/0.0.4-SNAPSHOT
[495/506] test-runner[3.0.2].publishLocalNoFluff 
Publishing Artifact(org.virtuslab.scala-cli,test-runner_3,0.0.4-SNAPSHOT) to ivy repo /Users/maman/Documents/scala-cli/out/repo/0.0.4-SNAPSHOT
[505/506] cli.run 
Exception in thread "main" java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:208)
	at scala.build.preprocessing.ScalaPreprocessor$.$anonfun$processSpecialImports$15(ScalaPreprocessor.scala:301)
	at scala.build.preprocessing.ScalaPreprocessor$.$anonfun$processSpecialImports$15$adapted(ScalaPreprocessor.scala:299)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.build.preprocessing.ScalaPreprocessor$.scala$build$preprocessing$ScalaPreprocessor$$processSpecialImports(ScalaPreprocessor.scala:299)
	at scala.build.preprocessing.ScalaPreprocessor$stateMachine$async$3.apply(ScalaPreprocessor.scala:124)
	at scala.build.EitherStateMachine.start(EitherCps.scala:59)
	at scala.build.preprocessing.ScalaPreprocessor$.process(ScalaPreprocessor.scala:117)
	at scala.build.preprocessing.ScalaPreprocessor$stateMachine$async$1.apply(ScalaPreprocessor.scala:55)
	at scala.build.EitherStateMachine.start(EitherCps.scala:59)
	at scala.build.preprocessing.ScalaPreprocessor$.preprocess(ScalaPreprocessor.scala:49)
	at scala.build.CrossSources$stateMachine$async$1.$anonfun$forInputs$5(CrossSources.scala:76)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
	at scala.collection.Iterator.toStream(Iterator.scala:1417)
	at scala.collection.Iterator.toStream$(Iterator.scala:1416)
	at scala.collection.AbstractIterator.toStream(Iterator.scala:1431)
	at scala.build.CrossSources$stateMachine$async$1.$anonfun$forInputs$4(CrossSources.scala:76)
	at scala.collection.immutable.List.map(List.scala:293)
	at scala.build.CrossSources$stateMachine$async$1.apply(CrossSources.scala:75)
	at scala.build.EitherStateMachine.start(EitherCps.scala:59)
	at scala.build.CrossSources$.forInputs(CrossSources.scala:71)
	at scala.build.Build$stateMachine$async$1.apply(Build.scala:118)
	at scala.build.EitherStateMachine.start(EitherCps.scala:59)
	at scala.build.Build$.scala$build$Build$$build(Build.scala:113)
	at scala.build.Build$.$anonfun$build$4(Build.scala:236)
	at scala.build.bloop.BloopServer$.withBuildServer(BloopServer.scala:200)
	at scala.build.Build$.build(Build.scala:229)
	at scala.build.Build$.build(Build.scala:248)
	at scala.cli.commands.Test$.run(Test.scala:55)
	at scala.cli.commands.Test$.run(Test.scala:8)
	at caseapp.core.app.CaseApp.main(CaseApp.scala:150)
	at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:112)
	at scala.cli.ScalaCli$.main(ScalaCli.scala:96)
	at scala.cli.ScalaCli.main(ScalaCli.scala)
1 targets failed
cli.run subprocess failed
```

There are 2 problems with it:
- i don't see a position where user made an error which makes it super difficult to fix
- error is not related to the reason why it was thrown

**Comment by romanowski** [comment]
@MarcinAman I think this is realated to running scala-cli from within mill (in a developer mode). I tried your code with `0.0.7` and it gives me a proper error message (see below). Probably the wording should be better but the preferred solution are using directives not the ammonite-style imports.

```
[error] ./pg.scala:1:8: an identifier expected, but string interpolator found
[error] import $ivy"com.novocode:junit-interface:0.11"
[error]        ^^^^
[error] ./pg.scala:2:8: value junit is not a member of org
[error] import org.junit.Test
[error]        ^^^^^^^^^
[error] ./pg.scala:3:8: value junit is not a member of org
[error] import org.junit.Assert.*
[error]        ^^^^^^^^^

```
