### ISSUE TITLE
ClassNotFoundException with sttp dependency and repl

### ISSUE THREAD

**Issue by bishabosha** [VirtusLab/scala-cli#2029]
**Version(s)**
1.0.0-RC1

**Describe the bug**
I try to use `sttp:4.0.0-RC1` with the repl, and get a ClassNotFoundException when accessing the status code of the response

**To Reproduce**
```scala
$ scala --dependency "com.softwaremill.sttp.client4::core:4.0.0-M1"
scala> import sttp.client4.quick.*
scala> val resp = quickRequest.get(uri"https://www.wikipedia.org").send()
scala> resp.code // CRASHES
Exception in thread "main" java.lang.ClassNotFoundException: StatusCode
	at dotty.tools.repl.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:51)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at dotty.tools.repl.AbstractFileClassLoader.loadClass(AbstractFileClassLoader.scala:57)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:495)
	at java.base/java.lang.Class.forName(Class.java:474)
	at dotty.tools.repl.Rendering.rewrapValueClass(Rendering.scala:135)
	at dotty.tools.repl.Rendering.$anonfun$4(Rendering.scala:114)
	at scala.Option.flatMap(Option.scala:283)
	at dotty.tools.repl.Rendering.valueOf(Rendering.scala:114)
	at dotty.tools.repl.Rendering.renderVal(Rendering.scala:157)
	at dotty.tools.repl.ReplDriver.$anonfun$7(ReplDriver.scala:365)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.repl.ReplDriver.extractAndFormatMembers$1(ReplDriver.scala:371)
	at dotty.tools.repl.ReplDriver.renderDefinitions$$anonfun$2(ReplDriver.scala:403)
	at scala.Option.map(Option.scala:242)
	at dotty.tools.repl.ReplDriver.renderDefinitions(ReplDriver.scala:409)
	at dotty.tools.repl.ReplDriver.compile$$anonfun$2(ReplDriver.scala:307)
	at scala.util.Either.fold(Either.scala:189)
	at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:323)
	at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:248)
	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:168)
	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:171)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:191)
	at dotty.tools.repl.ReplDriver.runBody$$anonfun$1(ReplDriver.scala:179)
	at dotty.tools.runner.ScalaClassLoader$.asContext(ScalaClassLoader.scala:80)
	at dotty.tools.repl.ReplDriver.runBody(ReplDriver.scala:179)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:171)
	at dotty.tools.repl.ReplDriver.tryRunning(ReplDriver.scala:133)
	at dotty.tools.repl.Main$.main(Main.scala:7)
	at dotty.tools.repl.Main.main(Main.scala)
```

**Expected behaviour**
no classpath issue, e.g. when I create a source file with the same code and run it

**Comment by bishabosha** [comment]
I'll close because this still crashes with the raw java command
```scala
java -cp $(cs fetch -p "org.scala-lang:scala3-compiler_3:3.2.2") dotty.tools.MainGenericRunner -cp $(cs fetch -p "com.softwaremill.sttp.client4::core:4.0.0-M1") -usejavacp
```
