### ISSUE TITLE
scala-cli config --create-pgp-key fails when using Java 8

### ISSUE THREAD

**Issue by alexarchambault** [VirtusLab/scala-cli#2035]
**Version(s)**
`1.0.0-RC1`

**Describe the bug**
When using a pre-installed JDK 8, running `scala-cli config --create-pgp-key` fails with a `ClassNotFoundException` (on my x86_64 Mac at least).

**To Reproduce**
```text
$ java -version
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (Temurin)(build 25.362-b09, mixed mode)

$ scala-cli config --create-pgp-key
Exception in thread "main" java.lang.NoClassDefFoundError: java/util/HexFormat
	at scala.cli.signing.commands.PgpCreate$.tryRun(PgpCreate.scala:53)
	at scala.cli.signing.commands.PgpCreate$.run(PgpCreate.scala:23)
	at scala.cli.signing.commands.PgpCreate$.run(PgpCreate.scala:22)
	at caseapp.core.app.CaseApp.main(CaseApp.scala:162)
	at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:115)
	at scala.cli.signing.ScalaCliSigning$.main(ScalaCliSigning.scala:35)
	at scala.cli.signing.ScalaCliSigning.main(ScalaCliSigning.scala)
Caused by: java.lang.ClassNotFoundException: java.util.HexFormat
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more
[error]  Failed to create PGP key pair (see messages above, scala-cli-signing return code: 1)
```

**Expected behaviour**
That command should succeed in creating a PGP key in the Scala CLI config.

**Comment by alexarchambault** [comment]
I'd have expected a native binary to be launched here, so that the JVM version doesn't matter much

**Comment by MaciejG604** [comment]
@alexarchambault Could you provide the output of running `scala-cli config --create-pgp-key -v -v` (possibly with e.g.`--pgp-password=none` required)? Are you sure you're using x86_64 architecture?
