### ISSUE TITLE
Poor error reporting in case of issue with the NFS daemon

### ISSUE THREAD

**Issue by julienrf** [VirtusLab/scala-cli#2044]
Here is the output of `scala-cli run -v -v -v -v my-script.sc`:

~~~ text
Exception in thread "main" java.lang.Exception: libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905
        at bloop.Bloop$.loop$1(Bloop.scala:104)
        at bloop.Bloop$.main(Bloop.scala:113)
        at bloop.Bloop.main(Bloop.scala)
Caused by: libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905
        at libdaemonjvm.server.Lock$.ifProcessRunning$1(Lock.scala:59)
        at libdaemonjvm.server.Lock$.$anonfun$tryAcquire$6(Lock.scala:76)
        at libdaemonjvm.server.Lock$.$anonfun$tryAcquire$6$adapted(Lock.scala:75)
        at scala.Option.flatMap(Option.scala:271)
        at libdaemonjvm.server.Lock$.ifFiles$1(Lock.scala:75)
        at libdaemonjvm.server.Lock$.tryAcquire(Lock.scala:94)
        at bloop.Bloop$.loop$1(Bloop.scala:95)
        ... 2 more
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.UnixDomainSockets.connect0(Native Method)
        at java.base/sun.nio.ch.UnixDomainSockets.connect(UnixDomainSockets.java:148)
        at java.base/sun.nio.ch.UnixDomainSockets.connect(UnixDomainSockets.java:144)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:851)
        at libdaemonjvm.internal.Java16SocketHandler$.client(Java16SocketHandler.scala:22)
        at libdaemonjvm.internal.SocketHandler$.client(SocketHandler.scala:18)
        at libdaemonjvm.internal.SocketFile$.connect(SocketFile.scala:23)
        at libdaemonjvm.internal.SocketFile$.canConnect(SocketFile.scala:14)
        at libdaemonjvm.server.Lock$.ifProcessRunning$1(Lock.scala:57)
        ... 8 more
Checking for a running Bloop server at /home/julien/.local/share/scalacli/bloop/daemon ...
Attempting to connect to Bloop server /home/julien/.local/share/scalacli/bloop/daemon ...
Connection attempt result: None
Bloop server exited with code 1
Running
  scala-cli bloop output
might give more details.
Exception in thread "main" scala.build.blooprifle.FailedToStartServerExitCodeException: Server failed with exit code 1
        at scala.build.blooprifle.internal.Operations$.check0$1$$anonfun$1(Operations.scala:250)
        at scala.build.blooprifle.BloopRifleLogger.runnable$$anonfun$1(BloopRifleLogger.scala:14)
        at java.base@17.0.5/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base@17.0.5/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base@17.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
~~~

Then, `scala-cli --power bloop output` gives the following (which I am not sure how to interpret):

~~~ text
[0.001s][warning][gc,jvmci] Setting EnableJVMCI to false as selected GC does not support JVMCI: z gc
Bloop server PID: 15304
Ignoring SIGINT
Will truncate output file /home/julien/.local/share/scalacli/bloop/daemon/output every 5 minutes
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905, trying again in 3 seconds
Exception in thread "main" java.lang.Exception: libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905
        at bloop.Bloop$.loop$1(Bloop.scala:104)
        at bloop.Bloop$.main(Bloop.scala:113)
        at bloop.Bloop.main(Bloop.scala)
Caused by: libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905
        at libdaemonjvm.server.Lock$.ifProcessRunning$1(Lock.scala:59)
        at libdaemonjvm.server.Lock$.$anonfun$tryAcquire$6(Lock.scala:76)
        at libdaemonjvm.server.Lock$.$anonfun$tryAcquire$6$adapted(Lock.scala:75)
        at scala.Option.flatMap(Option.scala:271)
        at libdaemonjvm.server.Lock$.ifFiles$1(Lock.scala:75)
        at libdaemonjvm.server.Lock$.tryAcquire(Lock.scala:94)
        at bloop.Bloop$.loop$1(Bloop.scala:95)
        ... 2 more
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.UnixDomainSockets.connect0(Native Method)
        at java.base/sun.nio.ch.UnixDomainSockets.connect(UnixDomainSockets.java:148)
        at java.base/sun.nio.ch.UnixDomainSockets.connect(UnixDomainSockets.java:144)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:851)
        at libdaemonjvm.internal.Java16SocketHandler$.client(Java16SocketHandler.scala:22)
        at libdaemonjvm.internal.SocketHandler$.client(SocketHandler.scala:18)
        at libdaemonjvm.internal.SocketFile$.connect(SocketFile.scala:23)
        at libdaemonjvm.internal.SocketFile$.canConnect(SocketFile.scala:14)
        at libdaemonjvm.server.Lock$.ifProcessRunning$1(Lock.scala:57)
        ... 8 more
~~~

_Originally posted by @julienrf in https://github.com/VirtusLab/scala-cli/issues/599#issuecomment-1513311052_

See the referenced issue for more details.

**Comment by Gedochao** [comment]
Why NFS daemon? 
Do you have any suspicions on what's causing it?

**Comment by julienrf** [comment]
The PID of the process shown in the log was the PID of the NFS daemon. I had to restart it to make it work. See https://github.com/VirtusLab/scala-cli/issues/599#issuecomment-1514320840

**Comment by sbrunk** [comment]
I just ran into the same issue after upgrading my machine to Ubuntu 23.04. In my case it was another process though:
```
17672 ?        Sl     0:00 /usr/share/code/chrome_crashpad_handler
```
After killing that process it's working again.

**Comment by andrzejressel** [comment]
I got the same on my Windows 11 machine today:
```
Connection attempt result: Some(Left(libdaemonjvm.client.ConnectError$ZombieFound: Cannot connect to process 10820))
Checking for a running Bloop server at C:\Users\andrz\AppData\Local\ScalaCli\data\bloop\daemon ...
Attempting to connect to Bloop server C:\Users\andrz\AppData\Local\ScalaCli\data\bloop\daemon ...
Connection attempt result: Some(Left(libdaemonjvm.client.ConnectError$ZombieFound: Cannot connect to process 10820))
Checking for a running Bloop server at C:\Users\andrz\AppData\Local\ScalaCli\data\bloop\daemon ...
Attempting to connect to Bloop server C:\Users\andrz\AppData\Local\ScalaCli\data\bloop\daemon ...
```

But it's steam:
```
PS C:\Users\andrz> tasklist /svc /FI "PID eq 10820"

Image Name                     PID Services
========================= ======== ============================================
steamwebhelper.exe           10820 N/A
```

Removing `C:\Users\andrz\AppData\Local\ScalaCli\data\bloop` fixed that - pid was saved there
