### ISSUE TITLE
jgit errors when publishing with Scala CLI 1.0.0

### ISSUE THREAD

**Issue by alexarchambault** [VirtusLab/scala-cli#2151]
**Version(s)**
`1.0.0` (`1.0.0-RC2` is fine)

**Describe the bug**
When trying to publish a project with Scala CLI, we get weird jgit errors, like
```
$ scala-cli publish .
Exception in thread "main" java.lang.IllegalArgumentException: Enumerated values of type org.eclipse.jgit.lib.CoreConfig$LogRefUpdates not available
	at org.eclipse.jgit.lib.Config.allValuesOf(Config.java:427)
	at org.eclipse.jgit.lib.Config.getEnum(Config.java:414)
	at org.eclipse.jgit.lib.CoreConfig.<init>(CoreConfig.java:193)
	at org.eclipse.jgit.lib.Config.get(Config.java:680)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.getCommitGraph(ObjectDirectory.java:239)
	at org.eclipse.jgit.internal.storage.file.WindowCursor.getCommitGraph(WindowCursor.java:102)
	at org.eclipse.jgit.revwalk.RevWalk.commitGraph(RevWalk.java:1178)
	at org.eclipse.jgit.revwalk.RevWalk.createCommit(RevWalk.java:1702)
	at org.eclipse.jgit.revwalk.RevWalk.lookupCommit(RevWalk.java:902)
	at org.eclipse.jgit.api.LogCommand.add(LogCommand.java:343)
	at org.eclipse.jgit.api.LogCommand.add(LogCommand.java:180)
	at org.eclipse.jgit.api.LogCommand.call(LogCommand.java:133)
	at scala.build.options.publish.ComputeVersion$GitTag.get$$anonfun$1(ComputeVersion.scala:68)
	at scala.util.Using$.resource(Using.scala:261)
	at scala.build.options.publish.ComputeVersion$GitTag.get(ComputeVersion.scala:138)
	at scala.cli.commands.publish.Publish$.orgNameVersion(Publish.scala:492)
	at scala.cli.commands.publish.Publish$.buildFileSet$$anonfun$1(Publish.scala:527)
	at scala.build.EitherCps$Helper.apply(EitherCps.scala:19)
	at scala.cli.commands.publish.Publish$.buildFileSet(Publish.scala:714)
	at scala.cli.commands.publish.Publish$.$anonfun$92(Publish.scala:847)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:584)
	at scala.build.Ops$EitherIteratorOps$.sequence0$extension(Ops.scala:16)
	at scala.cli.commands.publish.Publish$.prepareFilesAndUpload$$anonfun$1(Publish.scala:849)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.build.EitherCps$Helper.apply(EitherCps.scala:19)
	at scala.cli.commands.publish.Publish$.prepareFilesAndUpload(Publish.scala:1121)
	at scala.cli.commands.publish.Publish$.maybePublish(Publish.scala:423)
	at scala.cli.commands.publish.Publish$.doRun(Publish.scala:335)
	at scala.cli.commands.publish.Publish$.runCommand(Publish.scala:250)
	at scala.cli.commands.publish.Publish$.runCommand(Publish.scala:194)
	at scala.cli.commands.ScalaCommand.run(ScalaCommand.scala:364)
	at scala.cli.commands.ScalaCommand.run(ScalaCommand.scala:348)
	at caseapp.core.app.CaseApp.main(CaseApp.scala:150)
	at scala.cli.commands.ScalaCommand.main(ScalaCommand.scala:333)
	at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:120)
	at scala.cli.ScalaCliCommands.main(ScalaCliCommands.scala:124)
	at scala.cli.ScalaCli$.main0(ScalaCli.scala:203)
	at scala.cli.ScalaCli$.main(ScalaCli.scala:107)
	at scala.cli.ScalaCli.main(ScalaCli.scala)
Caused by: java.lang.NoSuchMethodException: org.eclipse.jgit.lib.CoreConfig$LogRefUpdates.values()
	at java.base@17.0.6/java.lang.Class.getMethod(DynamicHub.java:2227)
	at org.eclipse.jgit.lib.Config.allValuesOf(Config.java:422)
	... 39 more
```

**To Reproduce**
Checkout [scala-cli/directive-handler](https://github.com/scala-cli/directive-handler). From it, run `CI=1 scala-cli publish .`. Set dummy values for most variables it asks.

**Expected behaviour**
Publishing succeeds in computing a version, and proceeds to publish the project.

**Comment by alexarchambault** [comment]
Seems it also happens with publish local:
```text
$ scala-cli publish local .
Using directive publish.version not set, assuming git:tag as publish.computeVersion
Error: java.lang.IllegalArgumentException: Enumerated values of type org.eclipse.jgit.lib.CoreConfig$LogRefUpdates not available
For more details, please see '.scala-build/stacktraces/1685026032-12455219915379887771.log'

$ cat .scala-build/stacktraces/1685026032-12455219915379887771.log
java.lang.IllegalArgumentException: Enumerated values of type org.eclipse.jgit.lib.CoreConfig$LogRefUpdates not available
  org.eclipse.jgit.lib.Config.allValuesOf(Config.java:427)
  org.eclipse.jgit.lib.Config.getEnum(Config.java:414)
  org.eclipse.jgit.lib.CoreConfig.<init>(CoreConfig.java:193)
  org.eclipse.jgit.lib.Config.get(Config.java:680)
  org.eclipse.jgit.internal.storage.file.ObjectDirectory.getCommitGraph(ObjectDirectory.java:239)
  org.eclipse.jgit.internal.storage.file.WindowCursor.getCommitGraph(WindowCursor.java:102)
  org.eclipse.jgit.revwalk.RevWalk.commitGraph(RevWalk.java:1178)
  org.eclipse.jgit.revwalk.RevWalk.createCommit(RevWalk.java:1702)
  org.eclipse.jgit.revwalk.RevWalk.parseNew(RevWalk.java:1123)
  org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:1110)
  org.eclipse.jgit.internal.storage.file.RefDirectory.doPeel(RefDirectory.java:540)
  org.eclipse.jgit.internal.storage.file.RefDirectory.peel(RefDirectory.java:520)
  scala.build.options.publish.ComputeVersion$GitTag.$anonfun$2(ComputeVersion.scala:61)
  scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594)
  scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608)
  scala.collection.mutable.Growable.addAll(Growable.scala:61)
  scala.collection.mutable.Growable.addAll$(Growable.scala:57)
  scala.collection.immutable.MapBuilderImpl.addAll(Map.scala:690)
  scala.collection.immutable.Map$.from(Map.scala:641)
  scala.collection.IterableOnceOps.toMap(IterableOnce.scala:1293)
  scala.collection.IterableOnceOps.toMap$(IterableOnce.scala:1292)
  scala.collection.AbstractIterator.toMap(Iterator.scala:1300)
  scala.build.options.publish.ComputeVersion$GitTag.get$$anonfun$1(ComputeVersion.scala:67)
  scala.util.Using$.resource(Using.scala:261)
  scala.build.options.publish.ComputeVersion$GitTag.get(ComputeVersion.scala:138)
  scala.cli.commands.publish.Publish$.orgNameVersion(Publish.scala:492)
  scala.cli.commands.publish.Publish$.buildFileSet$$anonfun$1(Publish.scala:527)
  scala.build.EitherCps$Helper.apply(EitherCps.scala:19)
  scala.cli.commands.publish.Publish$.buildFileSet(Publish.scala:714)
  scala.cli.commands.publish.Publish$.$anonfun$92(Publish.scala:847)
  scala.collection.Iterator$$anon$9.next(Iterator.scala:584)
  scala.build.Ops$EitherIteratorOps$.sequence0$extension(Ops.scala:16)
  scala.cli.commands.publish.Publish$.prepareFilesAndUpload$$anonfun$1(Publish.scala:849)
  scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
  scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
  scala.build.EitherCps$Helper.apply(EitherCps.scala:19)
  scala.cli.commands.publish.Publish$.prepareFilesAndUpload(Publish.scala:1121)
  scala.cli.commands.publish.Publish$.maybePublish(Publish.scala:423)
  scala.cli.commands.publish.Publish$.doRun(Publish.scala:335)
  scala.cli.commands.publish.PublishLocal$.runCommand(PublishLocal.scala:87)
  scala.cli.commands.publish.PublishLocal$.runCommand(PublishLocal.scala:29)
  scala.cli.commands.ScalaCommand.run(ScalaCommand.scala:364)
  scala.cli.commands.ScalaCommand.run(ScalaCommand.scala:348)
  caseapp.core.app.CaseApp.main(CaseApp.scala:150)
  scala.cli.commands.ScalaCommand.main(ScalaCommand.scala:333)
  caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:120)
  scala.cli.ScalaCliCommands.main(ScalaCliCommands.scala:124)
  scala.cli.ScalaCli$.main0(ScalaCli.scala:203)
  scala.cli.ScalaCli$.main(ScalaCli.scala:107)
  scala.cli.ScalaCli.main(ScalaCli.scala)
java.lang.NoSuchMethodException: org.eclipse.jgit.lib.CoreConfig$LogRefUpdates.values()
  java.base@17.0.6/java.lang.Class.getMethod(DynamicHub.java:2227)
  org.eclipse.jgit.lib.Config.allValuesOf(Config.java:422)
  org.eclipse.jgit.lib.Config.getEnum(Config.java:414)
  org.eclipse.jgit.lib.CoreConfig.<init>(CoreConfig.java:193)
  org.eclipse.jgit.lib.Config.get(Config.java:680)
  org.eclipse.jgit.internal.storage.file.ObjectDirectory.getCommitGraph(ObjectDirectory.java:239)
  org.eclipse.jgit.internal.storage.file.WindowCursor.getCommitGraph(WindowCursor.java:102)
  org.eclipse.jgit.revwalk.RevWalk.commitGraph(RevWalk.java:1178)
  org.eclipse.jgit.revwalk.RevWalk.createCommit(RevWalk.java:1702)
  org.eclipse.jgit.revwalk.RevWalk.parseNew(RevWalk.java:1123)
  org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:1110)
  org.eclipse.jgit.internal.storage.file.RefDirectory.doPeel(RefDirectory.java:540)
  org.eclipse.jgit.internal.storage.file.RefDirectory.peel(RefDirectory.java:520)
  scala.build.options.publish.ComputeVersion$GitTag.$anonfun$2(ComputeVersion.scala:61)
  scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594)
  scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608)
  scala.collection.mutable.Growable.addAll(Growable.scala:61)
  scala.collection.mutable.Growable.addAll$(Growable.scala:57)
  scala.collection.immutable.MapBuilderImpl.addAll(Map.scala:690)
  scala.collection.immutable.Map$.from(Map.scala:641)
  scala.collection.IterableOnceOps.toMap(IterableOnce.scala:1293)
  scala.collection.IterableOnceOps.toMap$(IterableOnce.scala:1292)
  scala.collection.AbstractIterator.toMap(Iterator.scala:1300)
  scala.build.options.publish.ComputeVersion$GitTag.get$$anonfun$1(ComputeVersion.scala:67)
  scala.util.Using$.resource(Using.scala:261)
  scala.build.options.publish.ComputeVersion$GitTag.get(ComputeVersion.scala:138)
  scala.cli.commands.publish.Publish$.orgNameVersion(Publish.scala:492)
  scala.cli.commands.publish.Publish$.buildFileSet$$anonfun$1(Publish.scala:527)
  scala.build.EitherCps$Helper.apply(EitherCps.scala:19)
  scala.cli.commands.publish.Publish$.buildFileSet(Publish.scala:714)
  scala.cli.commands.publish.Publish$.$anonfun$92(Publish.scala:847)
  scala.collection.Iterator$$anon$9.next(Iterator.scala:584)
  scala.build.Ops$EitherIteratorOps$.sequence0$extension(Ops.scala:16)
  scala.cli.commands.publish.Publish$.prepareFilesAndUpload$$anonfun$1(Publish.scala:849)
  scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
  scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
  scala.build.EitherCps$Helper.apply(EitherCps.scala:19)
  scala.cli.commands.publish.Publish$.prepareFilesAndUpload(Publish.scala:1121)
  scala.cli.commands.publish.Publish$.maybePublish(Publish.scala:423)
  scala.cli.commands.publish.Publish$.doRun(Publish.scala:335)
  scala.cli.commands.publish.PublishLocal$.runCommand(PublishLocal.scala:87)
  scala.cli.commands.publish.PublishLocal$.runCommand(PublishLocal.scala:29)
  scala.cli.commands.ScalaCommand.run(ScalaCommand.scala:364)
  scala.cli.commands.ScalaCommand.run(ScalaCommand.scala:348)
  caseapp.core.app.CaseApp.main(CaseApp.scala:150)
  scala.cli.commands.ScalaCommand.main(ScalaCommand.scala:333)
  caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:120)
  scala.cli.ScalaCliCommands.main(ScalaCliCommands.scala:124)
  scala.cli.ScalaCli$.main0(ScalaCli.scala:203)
  scala.cli.ScalaCli$.main(ScalaCli.scala:107)
  scala.cli.ScalaCli.main(ScalaCli.scala)
```

**Comment by tgodzik** [comment]
Looks like the upgrade of jgit caused it :/ Maybe it's an issue with adding some more values to reflection json?

**Comment by Gedochao** [comment]
> Looks like the upgrade of jgit caused it :/ Maybe it's an issue with adding some more values to reflection json?

It's almost certainly that

**Comment by Gedochao** [comment]
As a temporary workaround on `v1.0.0` it should be sufficient to set `publish.version` with a directive, instead of reading it from a git tag.
The fix is already on a PR.
