### ISSUE TITLE
Allow ivy-style resolution of dependencies

### ISSUE THREAD

**Issue by soujiro32167** [VirtusLab/scala-cli#2210]
**Version(s)**

1.0.1

**Describe the bug**

When I try to add an Ivy-style repository using `//> using repository my.ivy.repo`, I get an error 

**To Reproduce**

`producer.scala`:

```scala
case class Foo(x: Int, y: Int)
```

`consumer.scala`:

```scala
//> using repository http://localhost:8081/artifactory/ivy-releases
//> using dep "com.eli::foo:0.0.1"

import com.eli.Foo

object a {
    Foo(1, 2)
}
```

Running `scala-cli compile`

```
[error] ./consumer.scala:3:16
[error] Error downloading com.eli:foo_3:0.0.1
[error]   not found: /Users/ekasik/.ivy2/local/com.eli/foo_3/0.0.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/eli/foo_3/0.0.1/foo_3-0.0.1.pom
[error]   not found: http://localhost:8081/artifactory/ivy-release-local/com/eli/foo_3/0.0.1/foo_3-0.0.1.pom
[error]   not found: /Users/ekasik/Library/Caches/ScalaCli/local-repo/v1.0.1/com.eli/foo_3/0.0.1/ivys/ivy.xml
[error]   No fallback URL found
[error] //> using dep "com.eli::foo:0.0.1"
```

**Expected behaviour**

The dependency gets resolved correctly

**Comment by lwronski** [comment]
Thanks for reporting, @soujiro32167. To troubleshoot the issue, please try cleaning the cache by running ```scala-cli clean``` and then provide us with the detailed logs from `scala-cli` with increased verbosity. You can do this by running the following command:

```
scala-cli compile -v -v -v
```

**Comment by soujiro32167** [comment]
The problem here is (I think) that, for a repo defined using `using repository`, the resolver is a maven resolver only.

Take a look at the file being looked up. Some look for a `.pom` file (maven resolver), and others for `ivy.xml` (ivy resolver): 
```
[error]   not found: /Users/ekasik/.ivy2/local/com.eli/foo_3/0.0.1/ivys/ivy.xml <-- **ivy**
[error]   not found: https://repo1.maven.org/maven2/com/eli/foo_3/0.0.1/foo_3-0.0.1.pom <-- **pom**
[error]   not found: http://localhost:8081/artifactory/ivy-release-local/com/eli/foo_3/0.0.1/foo_3-0.0.1.pom <-- **pom**
[error]   not found: /Users/ekasik/Library/Caches/ScalaCli/local-repo/v1.0.1/com.eli/foo_3/0.0.1/ivys/ivy.xml <-- **ivy** 
```

If I could specify something like 
```
//> using repository.url http://localhost:8081/artifactory/ivy-releases
//> using repository.resolver ivy
```
That should be enough to tell the resolver what to look for, based on https://www.scala-sbt.org/1.x/docs/Resolvers.html#URL

**Comment by soujiro32167** [comment]
here is the verbose dump 
```
➜  utils scala-cli compile resolver.scala -v -v -v
Checking for a running Bloop server at /Users/ekasik/Library/Caches/ScalaCli/bloop/daemon ...
Attempting to connect to Bloop server /Users/ekasik/Library/Caches/ScalaCli/bloop/daemon ...
Connection attempt result: Some(Right(java.nio.channels.SocketChannel[connected local= remote=/Users/ekasik/Library/Caches/ScalaCli/bloop/daemon/socket]))
nailgun debug: Sending arguments '' to Nailgun server
nailgun debug: Sending environment variables to Nailgun server
nailgun debug: Sending working directory /Users/ekasik/dev/caesars/utils to Nailgun server
nailgun debug: Sending command to about Nailgun server
nailgun debug: Finished sending command information to Nailgun server
nailgun debug: Starting thread to read stdin...
nailgun debug: Received action Print([B@60f5172d) from Nailgun server
nailgun debug: Received action Print([B@5202845c) from Nailgun server
nailgun debug: Received action Print([B@48db8f45) from Nailgun server
nailgun debug: Received action Print([B@15d6f0b9) from Nailgun server
nailgun debug: Received action Print([B@66413b31) from Nailgun server
nailgun debug: Received action Print([B@1f06334e) from Nailgun server
nailgun debug: Received action Exit(0) from Nailgun server
nailgun debug: Waiting for stdin thread to finish...
nailgun debug: Waiting for heartbeat thread to finish...
nailgun debug: Returning exit code...
Checking for a running Bloop server at /Users/ekasik/Library/Caches/ScalaCli/bloop/daemon ...
Attempting to connect to Bloop server /Users/ekasik/Library/Caches/ScalaCli/bloop/daemon ...
Connection attempt result: Some(Right(java.nio.channels.SocketChannel[connected local= remote=/Users/ekasik/Library/Caches/ScalaCli/bloop/daemon/socket]))
Checking for a running Bloop server at /Users/ekasik/Library/Caches/ScalaCli/bloop/daemon ...
Attempting to connect to Bloop server /Users/ekasik/Library/Caches/ScalaCli/bloop/daemon ...
Connection attempt result: Some(Right(java.nio.channels.SocketChannel[connected local= remote=/Users/ekasik/Library/Caches/ScalaCli/bloop/daemon/socket]))
nailgun debug: Sending arguments '' to Nailgun server
nailgun debug: Sending environment variables to Nailgun server
nailgun debug: Sending working directory /Users/ekasik/dev/caesars/utils to Nailgun server
nailgun debug: Sending command to about Nailgun server
nailgun debug: Finished sending command information to Nailgun server
nailgun debug: Starting thread to read stdin...
nailgun debug: Received action Print([B@78b243ae) from Nailgun server
nailgun debug: Received action Print([B@36d77b6c) from Nailgun server
nailgun debug: Received action Print([B@7c4f016) from Nailgun server
nailgun debug: Received action Print([B@66f8d0c0) from Nailgun server
nailgun debug: Received action Print([B@198de956) from Nailgun server
nailgun debug: Received action Print([B@a5d2abe) from Nailgun server
nailgun debug: Received action Exit(0) from Nailgun server
nailgun debug: Waiting for stdin thread to finish...
nailgun debug: Waiting for heartbeat thread to finish...
nailgun debug: Returning exit code...
Opening BSP connection with bloop
Bloop BSP connection waiting at local:/Users/ekasik/Library/Caches/ScalaCli/bsp-sockets/proc-3595
BSP connection at /Users/ekasik/Library/Caches/ScalaCli/bsp-sockets/proc-3595 not found, waiting 100 milliseconds
nailgun debug: Sending arguments '--protocol local --socket /Users/ekasik/Library/Caches/ScalaCli/bsp-sockets/proc-3595' to Nailgun server
nailgun debug: Sending environment variables to Nailgun server
nailgun debug: Sending working directory /Users/ekasik/dev/caesars/utils/.scala-build to Nailgun server
nailgun debug: Sending command to bsp Nailgun server
nailgun debug: Finished sending command information to Nailgun server
nailgun debug: Starting thread to read stdin...
nailgun debug: Received action Print([B@70249467) from Nailgun server
The server is listening for incoming connections at local:///Users/ekasik/Library/Caches/ScalaCli/bsp-sockets/proc-3595...
BSP connection at /Users/ekasik/Library/Caches/ScalaCli/bsp-sockets/proc-3595 opened
Connected to Bloop via BSP at local:/Users/ekasik/Library/Caches/ScalaCli/bsp-sockets/proc-3595
Connected to Bloop via BSP at local:/Users/ekasik/Library/Caches/ScalaCli/bsp-sockets/proc-3595
nailgun debug: Received action Print([B@674e4038) from Nailgun server
Accepted incoming BSP client connection at local:///Users/ekasik/Library/Caches/ScalaCli/bsp-sockets/proc-3595
Sending buildInitialize BSP command to Bloop
nailgun debug: Received action Print([B@49ce1b1f) from Nailgun server
request received: build/initialize
nailgun debug: Received action Print([B@4595fe8a) from Nailgun server
BSP initialization handshake complete.
Fetching List(Dependency(org.scala-lang:scala3-compiler_3, 3.3.0, Configuration(), Set(), Publication(, Type(), Extension(), Classifier()), false, true)), adding List(MavenRepository(http://localhost:8081/artifactory/ivy-releases, None, None, true), IvyRepository(Pattern(List(Const(file:///Users/ekasik/Library/Caches/ScalaCli/local-repo/v1.0.1//), Var(organisation), Const(/), Var(module), Const(/), Opt(List(Const(scala_), Var(scalaVersion), Const(/))), Opt(List(Const(sbt_), Var(sbtVersion), Const(/))), Var(revision), Const(/), Var(type), Const(s/), Var(artifact), Opt(List(Const(-), Var(classifier))), Const(.), Var(ext))), None, None, true, true, true, false, None, true))
Found 13 artifacts:
  /Users/ekasik/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.3.0/scala3-compiler_3-3.3.0.jar
  /Users/ekasik/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.3.0/scala3-interfaces-3.3.0.jar
  /Users/ekasik/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.3.0/scala3-library_3-3.3.0.jar
  /Users/ekasik/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/tasty-core_3/3.3.0/tasty-core_3-3.3.0.jar
  /Users/ekasik/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/9.4.0-scala-1/scala-asm-9.4.0-scala-1.jar
  /Users/ekasik/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.3.5/compiler-interface-1.3.5.jar
  /Users/ekasik/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-reader/3.19.0/jline-reader-3.19.0.jar
  /Users/ekasik/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-terminal/3.19.0/jline-terminal-3.19.0.jar
  /Users/ekasik/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-terminal-jna/3.19.0/jline-terminal-jna-3.19.0.jar
  /Users/ekasik/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.jar
  /Users/ekasik/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.7.0/protobuf-java-3.7.0.jar
  /Users/ekasik/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/util-interface/1.3.0/util-interface-1.3.0.jar
  /Users/ekasik/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1.jar

Fetching List(Dependency(org.scala-lang:scala3-library_3, 3.3.0, Configuration(), Set(), Publication(, Type(), Extension(), Classifier()), false, true), Dependency(com.eli:foo_3, 0.0.1, Configuration(), Set(), Publication(, Type(), Extension(), Classifier()), false, true)), adding List(MavenRepository(http://localhost:8081/artifactory/ivy-releases, None, None, true), IvyRepository(Pattern(List(Const(file:///Users/ekasik/Library/Caches/ScalaCli/local-repo/v1.0.1//), Var(organisation), Const(/), Var(module), Const(/), Opt(List(Const(scala_), Var(scalaVersion), Const(/))), Opt(List(Const(sbt_), Var(sbtVersion), Const(/))), Var(revision), Const(/), Var(type), Const(s/), Var(artifact), Opt(List(Const(-), Var(classifier))), Const(.), Var(ext))), None, None, true, true, true, false, None, true))
Downloading 2 dependencies
nailgun debug: Received action Print([B@241d1479) from Nailgun server
BSP server stopped
nailgun debug: Received action Exit(0) from Nailgun server
nailgun debug: Waiting for stdin thread to finish...
nailgun debug: Waiting for heartbeat thread to finish...
nailgun debug: Returning exit code...
Exception in thread "main" java.lang.Exception: scala.build.errors.FetchingDependenciesError: Error downloading com.eli:foo_3:0.0.1
  not found: /Users/ekasik/.ivy2/local/com.eli/foo_3/0.0.1/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/com/eli/foo_3/0.0.1/foo_3-0.0.1.pom
  forbidden: http://localhost:8081/artifactory/ivy-releases/com/eli/foo_3/0.0.1/foo_3-0.0.1.pom
  not found: /Users/ekasik/Library/Caches/ScalaCli/local-repo/v1.0.1/com.eli/foo_3/0.0.1/ivys/ivy.xml
  No fallback URL found
        at scala.cli.internal.CliLogger.exit(CliLogger.scala:141)
        at scala.cli.commands.util.CommandHelpers$EitherBuildExceptionOps.orExit(CommandHelpers.scala:18)
        at scala.cli.commands.compile.Compile$.runCommand(Compile.scala:135)
        at scala.cli.commands.compile.Compile$.runCommand(Compile.scala:38)
        at scala.cli.commands.ScalaCommand.run(ScalaCommand.scala:364)
        at scala.cli.commands.ScalaCommand.run(ScalaCommand.scala:348)
        at caseapp.core.app.CaseApp.main(CaseApp.scala:150)
        at scala.cli.commands.ScalaCommand.main(ScalaCommand.scala:333)
        at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:120)
        at scala.cli.ScalaCliCommands.main(ScalaCliCommands.scala:124)
        at scala.cli.ScalaCli$.main0(ScalaCli.scala:203)
        at scala.cli.ScalaCli$.main(ScalaCli.scala:107)
        at scala.cli.ScalaCli.main(ScalaCli.scala)
Caused by: scala.build.errors.FetchingDependenciesError: Error downloading com.eli:foo_3:0.0.1
  not found: /Users/ekasik/.ivy2/local/com.eli/foo_3/0.0.1/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/com/eli/foo_3/0.0.1/foo_3-0.0.1.pom
  forbidden: http://localhost:8081/artifactory/ivy-releases/com/eli/foo_3/0.0.1/foo_3-0.0.1.pom
  not found: /Users/ekasik/Library/Caches/ScalaCli/local-repo/v1.0.1/com.eli/foo_3/0.0.1/ivys/ivy.xml
  No fallback URL found
        at scala.build.Artifacts$.fetch0$$anonfun$1$$anonfun$3(Artifacts.scala:516)
        at scala.util.Either$LeftProjection.map(Either.scala:614)
        at scala.build.Artifacts$.fetch0$$anonfun$1(Artifacts.scala:516)
        at scala.build.EitherCps$Helper.apply(EitherCps.scala:19)
        at scala.build.Artifacts$.fetch0(Artifacts.scala:518)
        at scala.build.Artifacts$.fetch$$anonfun$1(Artifacts.scala:453)
        at scala.build.EitherCps$Helper.apply(EitherCps.scala:19)
        at scala.build.Artifacts$.fetch(Artifacts.scala:456)
        at scala.build.Artifacts$.apply$$anonfun$1(Artifacts.scala:308)
        at scala.build.EitherCps$Helper.apply(EitherCps.scala:19)
        at scala.build.Artifacts$.apply(Artifacts.scala:375)
        at scala.build.options.BuildOptions.artifacts$$anonfun$1(BuildOptions.scala:396)
        at scala.build.EitherCps$Helper.apply(EitherCps.scala:19)
        at scala.build.options.BuildOptions.artifacts(BuildOptions.scala:399)
        at scala.build.Build$.prepareBuild$$anonfun$1(Build.scala:1003)
        at scala.build.EitherCps$Helper.apply(EitherCps.scala:19)
        at scala.build.Build$.prepareBuild(Build.scala:1036)
        at scala.build.Build$.buildOnce$$anonfun$1(Build.scala:1057)
        at scala.build.EitherCps$Helper.apply(EitherCps.scala:19)
        at scala.build.Build$.buildOnce(Build.scala:1115)
        at scala.build.Build$.build$$anonfun$2(Build.scala:444)
        at scala.build.EitherCps$Helper.apply(EitherCps.scala:19)
        at scala.build.Build$.build(Build.scala:471)
        at scala.build.Build$.doBuildScope$1$$anonfun$1(Build.scala:310)
        at scala.build.EitherCps$Helper.apply(EitherCps.scala:19)
        at scala.build.Build$.doBuildScope$1(Build.scala:313)
        at scala.build.Build$.doBuild$1$$anonfun$1(Build.scala:315)
        at scala.build.EitherCps$Helper.apply(EitherCps.scala:19)
        at scala.build.Build$.doBuild$1(Build.scala:373)
        at scala.build.Build$.buildScopes$1$$anonfun$1(Build.scala:377)
        at scala.build.EitherCps$Helper.apply(EitherCps.scala:19)
        at scala.build.Build$.buildScopes$1(Build.scala:404)
        at scala.build.Build$.build$$anonfun$1(Build.scala:406)
        at scala.build.EitherCps$Helper.apply(EitherCps.scala:19)
        at scala.build.Build$.build(Build.scala:418)
        at scala.build.Build$.build$$anonfun$3(Build.scala:580)
        at scala.build.compiler.ScalaCompilerMaker.withCompiler(ScalaCompilerMaker.scala:31)
        at scala.build.compiler.ScalaCompilerMaker.withCompiler$(ScalaCompilerMaker.scala:7)
        at scala.build.compiler.BloopCompilerMaker.withCompiler(BloopCompilerMaker.scala:10)
        at scala.build.Build$.build(Build.scala:601)
        at scala.cli.commands.compile.Compile$.runCommand(Compile.scala:134)
        ... 10 more
Caused by: coursier.error.ResolutionError$CantDownloadModule: Error downloading com.eli:foo_3:0.0.1
  not found: /Users/ekasik/.ivy2/local/com.eli/foo_3/0.0.1/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/com/eli/foo_3/0.0.1/foo_3-0.0.1.pom
  forbidden: http://localhost:8081/artifactory/ivy-releases/com/eli/foo_3/0.0.1/foo_3-0.0.1.pom
  not found: /Users/ekasik/Library/Caches/ScalaCli/local-repo/v1.0.1/com.eli/foo_3/0.0.1/ivys/ivy.xml
  No fallback URL found
        at coursier.Resolve$.$anonfun$validate$1(Resolve.scala:367)
        at scala.collection.immutable.List.map(List.scala:246)
        at scala.collection.immutable.List.map(List.scala:79)
        at coursier.Resolve$.validate(Resolve.scala:365)
        at coursier.Resolve.validate0$1(Resolve.scala:137)
        at coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:187)
        at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
        at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
        at coursier.util.Task$.wrap(Task.scala:82)
        at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
        at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.6/java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

adding List(**MavenRepository(http://localhost:8081/artifactory/ivy-releases, None, None, true)**, IvyRepository(Pattern(List(Const(file:///Users/ekasik/Library/Caches/ScalaCli/local-repo/v1.0.1//)

**Comment by lwronski** [comment]
Hi @soujiro32167, I've found a possible solution in the coursier source code for parsing the repository as IvyRepository instead of MavenRepository. Could you test it with this syntax?

```
//> using repository ivy:http://localhost:8081/artifactory/ivy-releases
```

**Comment by soujiro32167** [comment]
We're making progress!
```
 adding List(IvyRepository(Pattern(List(Const(http://localhost:8081/repository/ivy-releases)))
```

Its still not finding the dependency though. I think its looking for some kind of pattern, rather than the repo path

**Comment by soujiro32167** [comment]
Found a way to make it work!
```
//> using repository ivy:http://localhost:8081/repository/ivy-releases/[organisation]/[module]/([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
```

Obviously its ugly because you have to add the pattern, but it does resolve!

**Comment by tgodzik** [comment]
It might be my ignorance speaking, but don't you have to add the pattern for ivy repositories always? https://ant.apache.org/ivy/history/latest-milestone/concept.html

**Comment by soujiro32167** [comment]
Could be @tgodzik. In fact, I think `sbt` has been providing them: https://www.scala-sbt.org/1.x/docs/Resolvers.html

```scala
resolvers += Resolver.url("my-test-repo", url)(Resolver.ivyStylePatterns)
```

**Comment by tgodzik** [comment]
Ah ok, so it seems there is a default `"[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]"`. Not sure how we can sensibly provide a default in ScalaCLI, but it would certainly be an enhancement

**Comment by MaciejG604** [comment]
This should work:
```
//> using repository ivy:http://localhost:8081/repository/ivy-releases/[defaultPattern]
```
It gets extended to `[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]` according to [Coursier's code](https://github.com/coursier/coursier/blob/3b997f788c99fd31cd238a17350b43dff5b98150/modules/core/shared/src/main/scala/coursier/ivy/Pattern.scala#L236)

@soujiro32167 could you confirm?

This could be added as a default if the supplied repository starts with `ivy:` and does not contain any pattern chunks, 
although I think `[defaultPattern]` is quite a good default as it is, it just needs some mentioning in the docs.

**Comment by soujiro32167** [comment]
interesting! I'll take a look

**Comment by MaciejG604** [comment]
I think the issue has been resolved. Don't hesitate to reopen the discussion if needed.
