### ISSUE TITLE
ZipException when packaging code with sttp to Scala Native

### ISSUE THREAD

**Issue by kciesielski** [VirtusLab/scala-cli#2258]
**Version(s)**
1.0.1
Platform: Linux, MacOS
JDK: OpenJDK 17.0.6

**Describe the bug**
This looks very similar to https://github.com/VirtusLab/scala-cli/issues/2166

Example script to reproduce:
```scala
//> using toolkit latest

import sttp.client4.*
import sttp.client4.curl.*
import sttp.client4.Response

object sttp4Native extends App:
    val backend = CurlBackend()
    val response: Response[String] = quickRequest
      .get(uri"http://icanhazip.com")
      .send(backend)

    println(response.body)
```

command:
`scala-cli --power package --native sttp.scala -f`

Error:
```
Exception in thread "main" java.util.zip.ZipException: invalid CEN header (bad signature)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1569)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:179)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:106)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)
        at scala.scalanative.io.VirtualDirectory$JarDirectory.liftedTree1$1(VirtualDirectory.scala:160)
        at scala.scalanative.io.VirtualDirectory$JarDirectory.<init>(VirtualDirectory.scala:157)
        at scala.scalanative.io.VirtualDirectory$.jar(VirtualDirectory.scala:57)
        at scala.scalanative.io.VirtualDirectory$.real(VirtualDirectory.scala:65)
        at scala.scalanative.linker.ClassLoader$.$anonfun$fromDisk$1(ClassLoader.scala:19)
        at scala.collection.immutable.List.map(List.scala:293)
        at scala.scalanative.linker.ClassLoader$.fromDisk(ClassLoader.scala:18)
        at scala.scalanative.linker.Link$.apply(Link.scala:13)
        at scala.scalanative.build.core.ScalaNative$.$anonfun$link$1(ScalaNative.scala:34)
        at scala.scalanative.build.Logger.time(Logger.scala:35)
        at scala.scalanative.build.Logger.time$(Logger.scala:32)
        at scala.scalanative.cli.utils.FilteredLogger.time(FilteredLogger.scala:7)
        at scala.scalanative.build.core.ScalaNative$.link(ScalaNative.scala:34)
        at scala.scalanative.build.Build$.$anonfun$build$1(Build.scala:71)
        at scala.scalanative.build.Logger.time(Logger.scala:35)
        at scala.scalanative.build.Logger.time$(Logger.scala:32)
        at scala.scalanative.cli.utils.FilteredLogger.time(FilteredLogger.scala:7)
        at scala.scalanative.build.Build$.build(Build.scala:61)
        at scala.scalanative.cli.ScalaNativeLd$.$anonfun$runLd$3(ScalaNativeLd.scala:73)
        at scala.scalanative.util.Scope$.apply(Scope.scala:32)
        at scala.scalanative.cli.ScalaNativeLd$.runLd(ScalaNativeLd.scala:72)
        at scala.scalanative.cli.ScalaNativeLd$.main(ScalaNativeLd.scala:42)
        at scala.scalanative.cli.ScalaNativeLd.main(ScalaNativeLd.scala)
Error: scala.build.errors.ScalaNativeBuildError: Error compiling with Scala Native
```

The issue seems to happen depending on file content. For example, changing `sttp4Native` main object name  is enough to make the compilation pass and a working binary  gets created. Different random correct changes in the code can affect the outcome. 

Working example:
```scala
//> using toolkit latest

import sttp.client4.*
import sttp.client4.curl.*
import sttp.client4.Response

object sttpClient4NativeWorkingExampleWithLongNameOfTheMainClass extends App:
    val backend = CurlBackend()
    val response: Response[String] = quickRequest
      .get(uri"http://icanhazip.com")
      .send(backend)

    println(response.body)
```

So far I'm noticing this only when using sttp.

**Comment by lwronski** [comment]
Hi @kciesielski Thanks for reporting,  I can reproduce the bug with the latest stable version of Scala CLI `1.0.1`. However, it seems to work fine with the nightly version of Scala CLI.
```
scala-cli --cli-version nightly  --power package --native sttp.scala -f
```

This resembles the bug in https://github.com/VirtusLab/scala-cli/issues/2166. It'll be fixed in the upcoming stable release.

**Comment by kciesielski** [comment]
Thanks, @lwronski, let me close the issue then :)
