### ISSUE TITLE
VirtualData corrupts binary files

### ISSUE THREAD

**Issue by JD557** [VirtusLab/scala-cli#2306]
**Version(s)**
v1.0.2

**Describe the bug**

Loading a gist with binary resources results in the data being corrupted.
I believe right now the resources are being loaded as [`VirtualData`](https://github.com/VirtusLab/scala-cli/blob/5afc7f39c3c76e9a5ee0c4f8882c2fba4eaf84c5/modules/build/src/main/scala/scala/build/input/Element.scala#L37), which later assumes that the content is [UTF-8 encoded](https://github.com/VirtusLab/scala-cli/blob/50815da25f02d53207215f993f461287f3a67722/modules/build/src/main/scala/scala/build/preprocessing/DataPreprocessor.scala#L28).

**To Reproduce**

Attempt to run `scala-cli --power --enable-markdown https://gist.github.com/JD557/4bd5b7acd53a08e8a9a306a2bde57a97`. It will fail with `Caused by: java.lang.Exception: Unsupported DIB header size: 12435439`

Downloading the zip and running it locally will work as expected.

**Expected behaviour**

The remote gist should run without corrupted files.

**Comment by tgodzik** [comment]
Thanks for reporting! Just to have everything in one place, the full stack trace:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at 1$minusquiz_md$Scope$.<clinit>(4bd5b7acd53a08e8a9a306a2bde57a97-main/1-quiz.md:217)
	at 1$minusquiz_md$.main(4bd5b7acd53a08e8a9a306a2bde57a97-main/1-quiz.md:1)
	at 1$minusquiz_md.main(4bd5b7acd53a08e8a9a306a2bde57a97-main/1-quiz.md)
Caused by: java.lang.Exception: Unsupported DIB header size: 12435439
	at eu.joaocosta.minart.graphics.image.Image$.loadImage$$anonfun$1(Image.scala:18)
	at scala.util.Success.flatMap(Try.scala:258)
	at eu.joaocosta.minart.graphics.image.Image$.loadImage(Image.scala:20)
	at eu.joaocosta.minart.graphics.image.Image$.loadBmpImage(Image.scala:31)
	at 1$minusquiz_md$Scope$MinartBackend$Font.<init>(4bd5b7acd53a08e8a9a306a2bde57a97-main/1-quiz.md:228)
	at 1$minusquiz_md$Scope$MinartBackend$Font$.apply(4bd5b7acd53a08e8a9a306a2bde57a97-main/1-quiz.md:227)
	at 1$minusquiz_md$Scope$MinartBackend$.<clinit>(4bd5b7acd53a08e8a9a306a2bde57a97-main/1-quiz.md:235)
	... 3 more

```
