### ISSUE TITLE
NoSuchFileException on diagnostic from macro

### ISSUE THREAD

**Issue by prolativ** [VirtusLab/scala-cli#2319]
**Version(s)**
1.0.2

**Describe the bug**
When compiling scala 3 code which contains an invocation of a macro whose inlined body produces a compiler diagnostic, scala-cli throws an exception displayed to the end user (even though this doesn't break the compilation by itself).

**To Reproduce**
`macro.scala`:
```scala
//> using scala "3.3.0"

import scala.quoted.*

opaque type MyString = String

inline def foo[A, B] = ${ fooImpl[A, B] }

def fooImpl[A: Type, B: Type](using Quotes) =
  '{ 
    val aOrB: A | B = ???
    aOrB match
      case a: A => ???
      case b: B => ???
   }
```

`usage.scala`:
```scala
val x = foo[MyString, Int]
```

Run:

```shell
scala-cli compile macro.scala usage.scala
```

Output:
```
Warning: setting /private/tmp/scala-cli-bug as the project root directory for this run.
Compiling project (Scala 3.3.0, JVM)
[warn] /Users/mpalka/Library/Caches/ScalaCli/bloop/macro.scala:1:1
[warn] the type test for MyString cannot be checked at runtime because it refers to an abstract type member or type parameter
Jul 28, 2023 12:32:56 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "build/publishDiagnostics",
  "params": {
    "textDocument": {
      "uri": "file:///Users/mpalka/Library/Caches/ScalaCli/bloop/macro.scala"
    },
    "buildTarget": {
      "uri": "file:/private/tmp/scala-cli-bug/.scala-build/?id\u003dscala-cli-bug_23be26abb2-ec79fc07fd"
    },
    "diagnostics": [
      {
        "range": {
          "start": {
            "line": 0,
            "character": 0
          },
          "end": {
            "line": 0,
            "character": 0
          }
        },
        "severity": 2,
        "message": "the type test for MyString cannot be checked at runtime because it refers to an abstract type member or type parameter"
      }
    ],
    "reset": true
  }
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
        at java.base@17.0.6/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base@17.0.6/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.6/java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:568)
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
        ... 13 more
Caused by: java.nio.file.NoSuchFileException: /Users/mpalka/Library/Caches/ScalaCli/bloop/macro.scala
        at java.base@17.0.6/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base@17.0.6/java.nio.file.Files.newByteChannel(Files.java:380)
        at java.base@17.0.6/java.nio.file.Files.newByteChannel(Files.java:432)
        at java.base@17.0.6/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
        at java.base@17.0.6/java.nio.file.Files.newInputStream(Files.java:160)
        at os.Path.getInputStream(Path.scala:498)
        at os.read$lines$stream$$anon$3.generate(ReadWriteOps.scala:361)
        at geny.Generator.foreach(Generator.scala:51)
        at geny.Generator.foreach$(Generator.scala:33)
        at os.read$lines$stream$$anon$3.foreach(ReadWriteOps.scala:359)
        at geny.Generator.toBuffer(Generator.scala:127)
        at geny.Generator.toBuffer$(Generator.scala:33)
        at os.read$lines$stream$$anon$3.toBuffer(ReadWriteOps.scala:359)
        at geny.Generator.toArray(Generator.scala:131)
        at geny.Generator.toArray$(Generator.scala:33)
        at os.read$lines$stream$$anon$3.toArray(ReadWriteOps.scala:359)
        at os.read$lines$.apply(ReadWriteOps.scala:346)
        at scala.build.ConsoleBloopBuildClient$.$anonfun$4$$anonfun$1(ConsoleBloopBuildClient.scala:194)
        at scala.Option.map(Option.scala:242)
        at scala.build.ConsoleBloopBuildClient$.$anonfun$4(ConsoleBloopBuildClient.scala:194)
        at scala.Option.flatMap(Option.scala:283)
        at scala.build.ConsoleBloopBuildClient$.printFileDiagnostic(ConsoleBloopBuildClient.scala:196)
        at scala.build.ConsoleBloopBuildClient.onBuildPublishDiagnostics$$anonfun$2(ConsoleBloopBuildClient.scala:86)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
        at scala.build.ConsoleBloopBuildClient.onBuildPublishDiagnostics(ConsoleBloopBuildClient.scala:87)
        ... 15 more
```

It looks like bloop is searching for the macro definition file somewhere in its cache (`/Users/mpalka/Library/Caches/ScalaCli/bloop/macro.scala`) but it can't find it there.
Also the position of the diagnostic in the request's body is wrong.

**Expected behaviour**
The diagnostic from the inlined macro should be printed properly as the compilation output to the console without any exception.

**Comment by lwronski** [comment]
This issue refer to diagnostics generated by the compiler, so I have move it to the dotty repo - https://github.com/lampepfl/dotty/issues/18323
