### ISSUE TITLE
Should not try to download the remote native-scala-fmt everytime

### ISSUE THREAD

**Issue by He-Pin** [VirtusLab/scala-cli#2379]
**Version(s)**
1.0.3
**Describe the bug**
![image](https://github.com/VirtusLab/scala-cli/assets/501740/68406e0d-bdd7-4702-9407-64b5be1fe754)
When I invoke `scala-cli fmt` , it will try to download everytime, if the network connection is bad, it will block, and I already downloaded that version of native image locally/ cached.

**To Reproduce**
Disconnect the network and invoke `scala-cli fmt` after the native image have been downloaded.

**Expected behaviour**
Use a local file to record and check if the native image is there before download.

**Comment by MaciejG604** [comment]
Could You provide me with the output of:
```
scala-cli fmt . -v -v -v
```

**Comment by He-Pin** [comment]
```
C:\Users\hepin>scala-cli -v -v -v
Fetching List(Dependency(org.scala-lang:scala3-compiler_3, 3.3.0, Configuration(), Set(), Publication(, Type(), Extension(), Classifier()), false, true)), adding List(IvyRepository(Pattern(List(Const(file:///C:/Users/hepin/AppData/Local/ScalaCli/cache/local-repo/1.0.4//), Var(organisation), Const(/), Var(module), Const(/), Opt(List(Const(scala_), Var(scalaVersion), Const(/))), Opt(List(Const(sbt_), Var(sbtVersion), Const(/))), Var(revision), Const(/), Var(type), Const(s/), Var(artifact), Opt(List(Const(-), Var(classifier))), Const(.), Var(ext))), None, None, true, true, true, false, None, true))
Found 13 artifacts:
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala3-compiler_3\3.3.0\scala3-compiler_3-3.3.0.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala3-interfaces\3.3.0\scala3-interfaces-3.3.0.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala3-library_3\3.3.0\scala3-library_3-3.3.0.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\tasty-core_3\3.3.0\tasty-core_3-3.3.0.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\modules\scala-asm\9.4.0-scala-1\scala-asm-9.4.0-scala-1.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-sbt\compiler-interface\1.3.5\compiler-interface-1.3.5.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\jline\jline-reader\3.19.0\jline-reader-3.19.0.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\jline\jline-terminal\3.19.0\jline-terminal-3.19.0.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\jline\jline-terminal-jna\3.19.0\jline-terminal-jna-3.19.0.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-library\2.13.10\scala-library-2.13.10.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\google\protobuf\protobuf-java\3.7.0\protobuf-java-3.7.0.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-sbt\util-interface\1.3.0\util-interface-1.3.0.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\net\java\dev\jna\jna\5.3.1\jna-5.3.1.jar

Fetching List(Dependency(org.scala-lang:scala3-library_3, 3.3.0, Configuration(), Set(), Publication(, Type(), Extension(), Classifier()), false, true)), adding List(IvyRepository(Pattern(List(Const(file:///C:/Users/hepin/AppData/Local/ScalaCli/cache/local-repo/1.0.4//), Var(organisation), Const(/), Var(module), Const(/), Opt(List(Const(scala_), Var(scalaVersion), Const(/))), Opt(List(Const(sbt_), Var(sbtVersion), Const(/))), Var(revision), Const(/), Var(type), Const(s/), Var(artifact), Opt(List(Const(-), Var(classifier))), Const(.), Var(ext))), None, None, true, true, true, false, None, true))
Fetching List(Dependency(org.scala-lang:scala3-library_3, 3.3.0, Configuration(), Set(), Publication(, Type(), Extension(), Classifier()), false, true), Dependency(org.scala-lang:scala3-compiler_3, 3.3.0, Configuration(), Set(), Publication(, Type(), Extension(), Classifier()), false, true)), adding List(IvyRepository(Pattern(List(Const(file:///C:/Users/hepin/AppData/Local/ScalaCli/cache/local-repo/1.0.4//), Var(organisation), Const(/), Var(module), Const(/), Opt(List(Const(scala_), Var(scalaVersion), Const(/))), Opt(List(Const(sbt_), Var(sbtVersion), Const(/))), Var(revision), Const(/), Var(type), Const(s/), Var(artifact), Opt(List(Const(-), Var(classifier))), Const(.), Var(ext))), None, None, true, true, true, false, None, true))
Found 13 artifacts:
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala3-library_3\3.3.0\scala3-library_3-3.3.0.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala3-compiler_3\3.3.0\scala3-compiler_3-3.3.0.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-library\2.13.10\scala-library-2.13.10.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala3-interfaces\3.3.0\scala3-interfaces-3.3.0.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\tasty-core_3\3.3.0\tasty-core_3-3.3.0.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\modules\scala-asm\9.4.0-scala-1\scala-asm-9.4.0-scala-1.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-sbt\compiler-interface\1.3.5\compiler-interface-1.3.5.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\jline\jline-reader\3.19.0\jline-reader-3.19.0.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\jline\jline-terminal\3.19.0\jline-terminal-3.19.0.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\jline\jline-terminal-jna\3.19.0\jline-terminal-jna-3.19.0.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\google\protobuf\protobuf-java\3.7.0\protobuf-java-3.7.0.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-sbt\util-interface\1.3.0\util-interface-1.3.0.jar
  C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\net\java\dev\jna\jna\5.3.1\jna-5.3.1.jar

  Running
C:\Users\hepin\.jdks\corretto-1.8.0_382\bin\java.exe
-Dscala.usejavacp=true
-cp
C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala3-library_3\3.3.0\scala3-library_3-3.3.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala3-compiler_3\3.3.0\scala3-compiler_3-3.3.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-library\2.13.10\scala-library-2.13.10.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala3-interfaces\3.3.0\scala3-interfaces-3.3.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\tasty-core_3\3.3.0\tasty-core_3-3.3.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\modules\scala-asm\9.4.0-scala-1\scala-asm-9.4.0-scala-1.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-sbt\compiler-interface\1.3.5\compiler-interface-1.3.5.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\jline\jline-reader\3.19.0\jline-reader-3.19.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\jline\jline-terminal\3.19.0\jline-terminal-3.19.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\jline\jline-terminal-jna\3.19.0\jline-terminal-jna-3.19.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\google\protobuf\protobuf-java\3.7.0\protobuf-java-3.7.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-sbt\util-interface\1.3.0\util-interface-1.3.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\net\java\dev\jna\jna\5.3.1\jna-5.3.1.jar
dotty.tools.repl.Main

Welcome to Scala 3.3.0 (1.8.0_382, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
```

**Comment by MaciejG604** [comment]
You forgot the `fmt` sub-command ->
```
scala-cli fmt . -v -v -v
```

**Comment by He-Pin** [comment]
And

```scala
C:\Users\hepin\IdeaProjects\incubator-pekko>scala-cli fmt . -v -v -v
Checking for .scalafmt.conf in cwd.
Getting https://github.com/virtuslab/scalafmt-native-image/releases/download/v3.7.11/scalafmt-x86_64-pc-win32.zip
https://github.com/virtuslab/scalafmt-native-image/releases/download/v3.7.11/scalafmt-x86_64-pc-win32.zip not found (coursier.cache.ArtifactError$NotFound: not found: https://github.com/virtuslab/scalafmt-native-image/releases/download/v3.7.11/scalafmt-x86_64-pc-win32.zip)
Could not fetch binary, fetching JVM dependencies:
  org.scalameta:scalafmt-cli_2.13:3.7.11

Launching scalafmt with command List(C:\Users\hepin\.jdks\corretto-1.8.0_382\bin\java.exe, -cp, C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\scalafmt-cli_2.13\3.7.11\scalafmt-cli_2.13-3.7.11.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-library\2.13.11\scala-library-2.13.11.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\scalafmt-core_2.13\3.7.11\scalafmt-core_2.13-3.7.11.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\scalafmt-dynamic_2.13\3.7.11\scalafmt-dynamic_2.13-3.7.11.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\svm-subs\101.0.0\svm-subs-101.0.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\googlecode\java-diff-utils\diffutils\1.3.0\diffutils-1.3.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\martiansoftware\nailgun-server\0.9.1\nailgun-server-0.9.1.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\github\scopt\scopt_2.13\4.1.0\scopt_2.13-4.1.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\scalafmt-sysops_2.13\3.7.11\scalafmt-sysops_2.13-3.7.11.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\scalafmt-config_2.13\3.7.11\scalafmt-config_2.13-3.7.11.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\scalameta_2.13\4.8.6\scalameta_2.13-4.8.6.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-reflect\2.13.11\scala-reflect-2.13.11.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\scalafmt-interfaces\3.7.11\scalafmt-interfaces-3.7.11.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\io\get-coursier\interface\0.0.17\interface-0.0.17.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\typesafe\config\1.4.2\config-1.4.2.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\modules\scala-parallel-collections_2.13\1.0.4\scala-parallel-collections_2.13-1.0.4.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\geirsson\metaconfig-core_2.13\0.11.1\metaconfig-core_2.13-0.11.1.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\geirsson\metaconfig-typesafe-config_2.13\0.11.1\metaconfig-typesafe-config_2.13-0.11.1.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\parsers_2.13\4.8.6\parsers_2.13-4.8.6.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scalap\2.13.11\scalap-2.13.11.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\geirsson\metaconfig-pprint_2.13\0.11.1\metaconfig-pprint_2.13-0.11.1.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\typelevel\paiges-core_2.13\0.4.2\paiges-core_2.13-0.4.2.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\modules\scala-collection-compat_2.13\2.5.0\scala-collection-compat_2.13-2.5.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\trees_2.13\4.8.6\trees_2.13-4.8.6.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-compiler\2.13.11\scala-compiler-2.13.11.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\lihaoyi\fansi_2.13\0.3.0\fansi_2.13-0.3.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\common_2.13\4.8.6\common_2.13-4.8.6.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\io\github\java-diff-utils\java-diff-utils\4.12\java-diff-utils-4.12.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\jline\jline\3.22.0\jline-3.22.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\net\java\dev\jna\jna\5.13.0\jna-5.13.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\lihaoyi\sourcecode_2.13\0.3.0\sourcecode_2.13-0.3.0.jar, org.scalafmt.cli.Cli)
  Running
C:\Users\hepin\.jdks\corretto-1.8.0_382\bin\java.exe
-cp
C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\scalafmt-cli_2.13\3.7.11\scalafmt-cli_2.13-3.7.11.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-library\2.13.11\scala-library-2.13.11.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\scalafmt-core_2.13\3.7.11\scalafmt-core_2.13-3.7.11.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\scalafmt-dynamic_2.13\3.7.11\scalafmt-dynamic_2.13-3.7.11.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\svm-subs\101.0.0\svm-subs-101.0.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\googlecode\java-diff-utils\diffutils\1.3.0\diffutils-1.3.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\martiansoftware\nailgun-server\0.9.1\nailgun-server-0.9.1.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\github\scopt\scopt_2.13\4.1.0\scopt_2.13-4.1.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\scalafmt-sysops_2.13\3.7.11\scalafmt-sysops_2.13-3.7.11.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\scalafmt-config_2.13\3.7.11\scalafmt-config_2.13-3.7.11.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\scalameta_2.13\4.8.6\scalameta_2.13-4.8.6.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-reflect\2.13.11\scala-reflect-2.13.11.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\scalafmt-interfaces\3.7.11\scalafmt-interfaces-3.7.11.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\io\get-coursier\interface\0.0.17\interface-0.0.17.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\typesafe\config\1.4.2\config-1.4.2.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\modules\scala-parallel-collections_2.13\1.0.4\scala-parallel-collections_2.13-1.0.4.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\geirsson\metaconfig-core_2.13\0.11.1\metaconfig-core_2.13-0.11.1.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\geirsson\metaconfig-typesafe-config_2.13\0.11.1\metaconfig-typesafe-config_2.13-0.11.1.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\parsers_2.13\4.8.6\parsers_2.13-4.8.6.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scalap\2.13.11\scalap-2.13.11.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\geirsson\metaconfig-pprint_2.13\0.11.1\metaconfig-pprint_2.13-0.11.1.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\typelevel\paiges-core_2.13\0.4.2\paiges-core_2.13-0.4.2.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\modules\scala-collection-compat_2.13\2.5.0\scala-collection-compat_2.13-2.5.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\trees_2.13\4.8.6\trees_2.13-4.8.6.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-compiler\2.13.11\scala-compiler-2.13.11.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\lihaoyi\fansi_2.13\0.3.0\fansi_2.13-0.3.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\common_2.13\4.8.6\common_2.13-4.8.6.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\io\github\java-diff-utils\java-diff-utils\4.12\java-diff-utils-4.12.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\jline\jline\3.22.0\jline-3.22.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\net\java\dev\jna\jna\5.13.0\jna-5.13.0.jar;C:\Users\hepin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\lihaoyi\sourcecode_2.13\0.3.0\sourcecode_2.13-0.3.0.jar
org.scalafmt.cli.Cli
```

&

```
--respect-project-filters
--config
C:\Users\hepin\IdeaProjects\incubator-pekko\.scala-build\.scalafmt.conf

Exception in thread "main" java.io.IOException: Cannot run program "C:\Users\hepin\.jdks\corretto-1.8.0_382\bin\java.exe" (in directory "C:\Users\hepin\IdeaProjects\incubator-pekko"): CreateProcess error=206, ??????????
        at java.base@17.0.6/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base@17.0.6/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at scala.build.internal.Runner$.run0(Runner.scala:91)
        at scala.build.internal.Runner$.maybeExec(Runner.scala:33)
        at scala.cli.commands.fmt.Fmt$.runCommand(Fmt.scala:118)
        at scala.cli.commands.fmt.Fmt$.runCommand(Fmt.scala:42)
        at scala.cli.commands.ScalaCommand.run(ScalaCommand.scala:364)
        at scala.cli.commands.ScalaCommand.run(ScalaCommand.scala:348)
        at caseapp.core.app.CaseApp.main(CaseApp.scala:150)
        at scala.cli.commands.ScalaCommand.main(ScalaCommand.scala:333)
        at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:120)
        at scala.cli.ScalaCliCommands.main(ScalaCliCommands.scala:125)
        at scala.cli.ScalaCli$.main0(ScalaCli.scala:245)
        at scala.cli.ScalaCli$.main(ScalaCli.scala:108)
        at scala.cli.ScalaCli.main(ScalaCli.scala)
Caused by: java.io.IOException: CreateProcess error=206, ??????????
        at com.oracle.svm.core.jni.functions.JNIFunctions$NewObjectWithObjectArrayArgFunctionPointer.invoke(JNIFunctions.java)
        at com.oracle.svm.core.jni.functions.JNIFunctions.ThrowNew(JNIFunctions.java:882)
        at java.base@17.0.6/java.lang.ProcessImpl.create(ProcessImpl.java)
        at java.base@17.0.6/java.lang.ProcessImpl.<init>(ProcessImpl.java:499)
        at java.base@17.0.6/java.lang.ProcessImpl.start(ProcessImpl.java:158)
        at java.base@17.0.6/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 14 more
```

**Comment by MaciejG604** [comment]
This should be fixed now, the native image artifacts were missing under v3.7.11.
So only one more download should be performed.

For the future uses you can pin the version of scalafmt so that no downloads are performed.
To do so, add `--scalafmt-version 3.7.11` flag to the `scala-cli fmt` sub-command:
```
scala-cli fmt --scalafmt-version 3.7.11
```
Or create a `.scalafmt.conf` configuration file in the root of the project:
```
echo 'version = "3.7.11"' > .scalafmt.conf
```

@He-Pin could you confirm the problem with 3.7.11 has been solved?

**Comment by He-Pin** [comment]
It's starting the download, let me verify it after The download is completed.
```
https://github.com/virtuslab/scalafmt-native-image/releases/download/v3.7.11/scalafmt-x86_64-pc-win32.zip
    1.0% [          ] 159.4 KiB (4.7 KiB / s)

```

**Comment by tgodzik** [comment]
@He-Pin did it download correctly?

**Comment by He-Pin** [comment]
Yes, it works now, thanks.
