### ISSUE TITLE
`fmt` throws unhelpful `IllegalArgumentException`

### ISSUE THREAD

**Issue by pawelprazak** [VirtusLab/scala-cli#2415]
**Version(s)**
Scala CLI version: 1.0.4
Scala version (default): 3.3.0

**Describe the bug**
Adding invalid path throws non-actionable error message with a cryptic stack trace.

**To Reproduce**
After adding the second line here:
```
project.excludePaths = [
    "glob:**/src/main/scala/besom/rpc/**.scala",
    "core/src/main/scala/besom/internal/Config.scala"
]
```

```
scala-cli fmt . --check -F --respect-project-filters
Exception in thread "main" java.lang.IllegalArgumentException
	at sun.nio.fs.UnixFileSystem.getPathMatcher(UnixFileSystem.java:286)
	at org.scalafmt.config.ProjectFiles$FileMatcher$Nio.<init>(ProjectFiles.scala:74)
	at org.scalafmt.config.ProjectFiles$FileMatcher$.$anonfun$nio$1(ProjectFiles.scala:70)
	at scala.collection.immutable.List.map(List.scala:250)
	at scala.collection.immutable.List.map(List.scala:79)
	at org.scalafmt.config.ProjectFiles$FileMatcher$.create(ProjectFiles.scala:69)
	at org.scalafmt.config.ProjectFiles$FileMatcher$.nio(ProjectFiles.scala:70)
	at org.scalafmt.config.ProjectFiles$FileMatcher$.apply(ProjectFiles.scala:64)
	at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$2(ScalafmtCoreRunner.scala:27)
	at metaconfig.Configured$ConfiguredImplicit.fold(Configured.scala:111)
	at org.scalafmt.cli.ScalafmtCoreRunner$.run(ScalafmtCoreRunner.scala:23)
	at org.scalafmt.cli.Cli$.runWithRunner(Cli.scala:140)
	at org.scalafmt.cli.Cli$.run(Cli.scala:91)
	at org.scalafmt.cli.Cli$.mainWithOptions(Cli.scala:61)
	at org.scalafmt.cli.Cli$.main(Cli.scala:43)
	at org.scalafmt.cli.Cli.main(Cli.scala)
```

**Expected behaviour**
Instead of a stack trace, it would be nice to get an actionable error message that user can use to correct their mistake, e.g.:
```
[project.excludePaths] Please prefix your path with 'glob:' or 'regex:', given path is invalid: 'core/src/main/scala/besom/internal/Config.scala'
```

For extra usability, I'd consider adding ability to allow user to use correct relative or absolute paths without any prefix, because the current behaviour is surprising to a new user.

**Comment by tgodzik** [comment]
Should be available in the next version of Scalafmt
