### ISSUE TITLE
Execution of Scala.js fails and hangs in release mode

### ISSUE THREAD

**Issue by keynmol** [VirtusLab/scala-cli#256]
I'm on Apple M1, java version is:

```
❯ java -version
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Temurin-17+35 (build 17+35)
OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode)
```

```
❯ cat js.scala
object Hello extends App {
  var i = 0
  while (i < 5) {
    println(i)
    i += 1
  }
}

❯ scala-cli clean js.scala && scala-cli js.scala --js --js-mode dev
Compiling project (Scala 3.0.2, Scala.JS)
Compiled project (Scala 3.0.2, Scala.JS)
0
1
2
3
4

❯ scala-cli clean js.scala && scala-cli js.scala --js --js-mode release
Compiling project (Scala 3.0.2, Scala.JS)
Compiled project (Scala 3.0.2, Scala.JS)
java.lang.ExceptionInInitializerError
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:315)
	at com.google.javascript.jscomp.DiagnosticGroups.<clinit>(DiagnosticGroups.java:233)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	at com.google.javascript.jscomp.CompilationLevel.applyFullCompilationOptions(CompilationLevel.java:179)
	at com.google.javascript.jscomp.CompilationLevel.setOptionsForCompilationLevel(CompilationLevel.java:86)
	at org.scalajs.linker.backend.closure.ClosureLinkerBackend.closureOptions(ClosureLinkerBackend.scala:219)
	at org.scalajs.linker.backend.closure.ClosureLinkerBackend.$anonfun$emit$5(ClosureLinkerBackend.scala:96)
	at org.scalajs.logging.Logger.time(Logger.scala:42)
	at org.scalajs.logging.Logger.time$(Logger.scala:40)
	at org.scalajs.logging.ScalaConsoleLogger.time(ScalaConsoleLogger.scala:15)
	at org.scalajs.linker.backend.closure.ClosureLinkerBackend.$anonfun$emit$3(ClosureLinkerBackend.scala:95)
	at scala.Option.map(Option.scala:230)
	at org.scalajs.linker.backend.closure.ClosureLinkerBackend.emit(ClosureLinkerBackend.scala:89)
	at org.scalajs.linker.standard.StandardLinkerImpl.$anonfun$link$2(StandardLinkerImpl.scala:47)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:567)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.google.javascript.rhino.Messages, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:932)
	at com.google.javascript.rhino.ErrorFormat.format(ErrorFormat.java:54)
	at com.google.javascript.rhino.SimpleErrorReporter.getMessage(SimpleErrorReporter.java:103)
	at com.google.javascript.rhino.SimpleErrorReporter.getMessage0(SimpleErrorReporter.java:95)
	at com.google.javascript.jscomp.RhinoErrorReporter.<clinit>(RhinoErrorReporter.java:136)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	... 25 more
```

P.S.: having tons of fun with this tool, absolute incredible addition to Scala tooling!

**Comment by tpasternak** [comment]
Just tried to reproduce it and I couldn't, probably it's an M1-only issue. @romanowski could you check it?

**Comment by scalway** [comment]
I've reproduced it on Ubuntu 21.10 / Intel.
