### ISSUE TITLE
Running with Scala Native 0.4.1 fails 

### ISSUE THREAD

**Issue by keynmol** [VirtusLab/scala-cli#261]
I know, I know... it's just been released :D 

```
❯ cat native.scala
object E extends App {
  println("hello!")
}

❯ scala-cli version
0.0.7

❯ scala-cli clean native.scala && scala-cli run native.scala -S 2.13 --native --native-version 0.4.1
Compiling project (Scala 2.13.6, Scala Native)
Compiled project (Scala 2.13.6, Scala Native)
Exception in thread "main" scala.MatchError: 170 (of class java.lang.Integer)
	at scala.scalanative.nir.serialization.BinaryDeserializer.getInst(BinaryDeserializer.scala:106)
	at scala.scalanative.nir.serialization.BinaryDeserializer.$anonfun$getInsts$1(BinaryDeserializer.scala:103)
	at scala.scalanative.nir.serialization.BinaryDeserializer.$anonfun$getSeq$1(BinaryDeserializer.scala:41)
	at scala.scalanative.nir.serialization.BinaryDeserializer.$anonfun$getSeq$1$adapted(BinaryDeserializer.scala:41)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.immutable.Range.foreach(Range.scala:158)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at scala.scalanative.nir.serialization.BinaryDeserializer.getSeq(BinaryDeserializer.scala:41)
	at scala.scalanative.nir.serialization.BinaryDeserializer.getInsts(BinaryDeserializer.scala:103)
	at scala.scalanative.nir.serialization.BinaryDeserializer.getDefn(BinaryDeserializer.scala:168)
	at scala.scalanative.nir.serialization.BinaryDeserializer.$anonfun$deserialize$1(BinaryDeserializer.scala:35)
```

## Expectation

Works as with 0.4.0:

```
❯ scala-cli clean native.scala && scala-cli run native.scala -S 2.13 --native --native-version 0.4.0
Compiling project (Scala 2.13.6, Scala Native)
Compiled project (Scala 2.13.6, Scala Native)
Linking (1772 ms)
Discovered 974 classes and 7887 methods
Generating intermediate code (1416 ms)
Produced 16 files
Compiling to native code (2167 ms)
Linking native code (immix gc, none lto) (193 ms)
Total (6075 ms)
hello!
```

**Comment by WojciechMazur** [comment]
Tag 170 refers to new a LinktimeIf, however it does not override any of existing Tags (value 170 was not used before). Can you check you're using in the build correct version 0.4.1 for `tools` and `nir` artifacts? Maybe there is some issue with the cache?

**Comment by keynmol** [comment]
I think whatever the issue is - I can't really control it from scala-cli, right? May be some weird internal resolution issue.

Happens in a clean folder:

```
❯ ll -a
total 0
drwx------     2 user  staff    64B 21 Oct 18:21 .
drwx------@ 1792 user  staff    56K 21 Oct 18:22 ..

❯ vim native.scala

❯ cat native.scala
object E extends App {
  println("hello!")
}

❯ scala-cli clean native.scala && scala-cli run native.scala -S 2.13 --native --native-version 0.4.1
Compiling project (Scala 2.13.6, Scala Native)
Compiled project (Scala 2.13.6, Scala Native)
Exception in thread "main" scala.MatchError: 170 (of class java.lang.Integer)
	at scala.scalanative.nir.serialization.BinaryDeserializer.getInst(BinaryDeserializer.scala:106)
	at scala.scalanative.nir.serialization.BinaryDeserializer.$anonfun$getInsts$1(BinaryDeserializer.scala:103)
	at scala.scalanative.nir.serialization.BinaryDeserializer.$anonfun$getSeq$1(BinaryDeserializer.scala:41)
```

I've confirmed that 0.4.1 works perfectly in an SBT project 👍 

On CI in fact: https://github.com/indoorvivants/sn-demangler/pull/1

So it's a scala-cli issue only

**Comment by WojciechMazur** [comment]
Version provided with `--native-version` argument overrides only runtime dependencies, eg. javalib, scalalib, etc. However `tools` used to perform actual linking and compilation are always using version defined for `Deps.nativeTools` (0.4.0). This version should be updated to 0.4.1. 
Updating version in the Deps is probably only a temporary solution, proper one should allow using the same version for runtime and linker when using --native-version argument
