### ISSUE TITLE
Error when run scala-cli xxx.sc on Windows11

### ISSUE THREAD

**Issue by He-Pin** [VirtusLab/scala-cli#2705]
verion:1.1
platform: Windows.

```scala
C:\Users\hepin\IdeaProjects\incubator-pekko\stream-tests\src\test\scala-jdk9-only\org\apache\pekko\stream\scaladsl>scala-cli bloop output
Bloop server PID: 17136
Ignoring SIGINT
Will truncate output file C:\Users\hepin\AppData\Local\ScalaCli\data\bloop\daemon\output every 5 minutes
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 31196, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 31196, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 31196, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 31196, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 31196, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 31196, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 31196, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 31196, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 31196, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 31196, trying again in 3 seconds
Exception in thread "main" java.lang.Exception: libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 31196
        at bloop.Bloop$.loop$1(Bloop.scala:102)
        at bloop.Bloop$.main(Bloop.scala:114)
        at bloop.Bloop.main(Bloop.scala)
Caused by: libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 31196
        at libdaemonjvm.server.Lock$.ifProcessRunning$1(Lock.scala:59)
        at libdaemonjvm.server.Lock$.$anonfun$tryAcquire$6(Lock.scala:76)
        at libdaemonjvm.server.Lock$.$anonfun$tryAcquire$6$adapted(Lock.scala:75)
        at scala.Option.flatMap(Option.scala:271)
        at libdaemonjvm.server.Lock$.ifFiles$1(Lock.scala:75)
        at libdaemonjvm.server.Lock$.tryAcquire(Lock.scala:94)
        at bloop.Bloop$.loop$1(Bloop.scala:93)
        ... 2 more
Caused by: java.net.ConnectException: Connection refused: connect
        at java.base/sun.nio.ch.UnixDomainSockets.connect0(Native Method)
        at java.base/sun.nio.ch.UnixDomainSockets.connect(UnixDomainSockets.java:154)
        at java.base/sun.nio.ch.UnixDomainSockets.connect(UnixDomainSockets.java:150)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:878)
        at libdaemonjvm.internal.Java16SocketHandler$.client(Java16SocketHandler.scala:22)
        at libdaemonjvm.internal.SocketHandler$.client(SocketHandler.scala:18)
        at libdaemonjvm.internal.SocketFile$.connect(SocketFile.scala:23)
        at libdaemonjvm.internal.SocketFile$.canConnect(SocketFile.scala:14)
        at libdaemonjvm.server.Lock$.ifProcessRunning$1(Lock.scala:57)
```

**Comment by Gedochao** [comment]
@He-Pin How do I replicate this? Can you share the script code, or some other pointers?

You seem to be doing something with JDK9 and Bloop doesn't seem to cooperate, but that's to vague to guess what's wrong. However:
- it breaks on something tied to the sockets, so a wild guess: are you using the default Bloop fork started by Scala CLI, or is it something custom? And what's the JVM Bloop runs on?
- since the problem is tied to Bloop, a possible workaround is to bypass Bloop with `--server=false`

**Comment by He-Pin** [comment]
Sorry for not inlcudes much infomation: @Gedochao 
Source: https://github.com/apache/incubator-pekko/blob/main/project/VerifyJDK9Classes.scala

Reproduce:
On Windows CMD, not WSL.

1. clone pekko:main  https://github.com/apache/incubator-pekko
2. sbt stream / compile
3. run `scala-cli stream/target/scala-cli/VerifyJDK9Classes-2.13.sc`
