### ISSUE TITLE
Default Bloop to tcp for non standard systems

### ISSUE THREAD

**Issue by ckipp01** [VirtusLab/scala-cli#271]
I've used Bloop before on FreeBSD so I figured I'd give this a shot. I was making a port for scala-cli and when trying to use the `scala-cli` artifact that is in the release page, and then trying to run it on FreeBSD results in the following:

```
> scala-cli run Hello.scala
Exception in thread "main" java.lang.UnsatisfiedLinkError
        at org.scalasbt.ipcsocket.NativeLoader.load(NativeLoader.java:104)
        at org.scalasbt.ipcsocket.JNIUnixDomainSocketLibraryProvider.<clinit>(JNIUnixDomainSocketLibraryProvider.java:78)
        at org.scalasbt.ipcsocket.UnixDomainSocketLibraryProvider.get(UnixDomainSocketLibraryProvider.java:26)
        at org.scalasbt.ipcsocket.UnixDomainSocket.<init>(UnixDomainSocket.java:50)
        at scala.build.blooprifle.internal.NamedSocketBuilder.create(NamedSocketBuilder.scala:15)
        at scala.build.blooprifle.internal.Operations$$anon$1.liftedTree1$1(Operations.scala:229)
        at scala.build.blooprifle.internal.Operations$$anon$1.openSocket(Operations.scala:227)
        at scala.build.blooprifle.BloopRifle$$anon$2.openSocket(BloopRifle.scala:130)
        at scala.build.bloop.BloopServer$.create$1(BloopServer.scala:76)
        at scala.build.bloop.BloopServer$.connect(BloopServer.scala:92)
        at scala.build.bloop.BloopServer$.bsp(BloopServer.scala:115)
        at scala.build.bloop.BloopServer$.buildServer(BloopServer.scala:133)
        at scala.build.bloop.BloopServer$.withBuildServer(BloopServer.scala:198)
        at scala.build.Build$.build(Build.scala:347)
        at scala.build.Build$.build(Build.scala:371)
        at scala.cli.commands.Run$.run(Run.scala:71)
        at scala.cli.commands.Run$.run(Run.scala:20)
        at scala.cli.commands.Run$.run(Run.scala:14)
        at caseapp.core.app.CaseApp.main(CaseApp.scala:150)
        at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:112)
        at scala.cli.ScalaCli$.main(ScalaCli.scala:97)
        at scala.cli.ScalaCli.main(ScalaCli.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at coursier.bootstrap.launcher.Bootstrap.main(Bootstrap.java:109)
        at coursier.bootstrap.launcher.ResourcesLauncher.main(ResourcesLauncher.java:79)
```

This happens for run, compile, etc. The `-h` does work though :).  Just throwing this up here in case it's a quick fix.

System details:

```
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (build 25.302-b08, mixed mode)

FreeBSD 12.2
```

**Comment by alexarchambault** [comment]
You might have a better luck with `--bloop-bsp-protocol tcp`. We need to default to it on non-"standard" systems.

**Comment by ckipp01** [comment]
```
chris@myHostName ~/s/scala-cli-test> ufetch

   _  _____  _   chris@myHostName
  / \`     `/ \  OS:        FreeBSD 12.2-RELEASE-p1
  \/       (__/  KERNEL:    GENERIC 1202000
  |           |  UPTIME:    5 days
  |           |  PACKAGES:  135
   \         /   SHELL:     fish
    `-_____-`

chris@myHostName ~/s/scala-cli-test> scala-cli run Hello.scala --bloop-bsp-protocol tcp
hello
```

😄 it works! I think I can probably claim to be first to run it on FreeBSD.

> We need to default to it on non-"standard" systems.

Cool, is this plan then to do it automatically? I can change the title to better reflect this to track it. I think after that's one I'll submit it to ports to people can just do a. `pkg install scala-cli` on FreeBSD then.

**Comment by alexarchambault** [comment]
> Cool, is this plan then to do it automatically?

Yeah, this can be changed around [here](https://github.com/VirtusLab/scala-cli/blob/86c837998ff655bba5e59e2154d02c188f698416/modules/cli/src/main/scala/scala/cli/commands/SharedCompilationServerOptions.scala#151).

Unless we can just use the newer domain socket support added in JDK 16 or 17 🤔 (so that we don't run into these JNI / JNA issues).
