### ISSUE TITLE
Scala CLI does not support dependencyModules

### ISSUE THREAD

**Issue by tgodzik** [VirtusLab/scala-cli#2792]
**Version(s)**
v1.2.0

**Describe the bug**

```
2024.03.10 14:35:44 INFO  Connected to Scala CLI server v1.1.3
2024.03.10 14:35:44 INFO  Scala CLI: Fatal error has occured within bloop bsp server, method: buildTargetDependencyModules, with params: DependencyModulesParams [
2024.03.10 14:35:44 INFO  Scala CLI:   targets = ArrayList (
2024.03.10 14:35:44 INFO  Scala CLI:     BuildTargetIdentifier [
2024.03.10 14:35:44 INFO  Scala CLI:       uri = "file:/home/runner/work/metals/metals/tests/unit/target/e2e/file-watcher/didChangeWatchedFiles-notification/.scala-build/?id=didChangeWatchedFiles-notification_f4dd477a3a"
2024.03.10 14:35:44 INFO  Scala CLI:     ],
2024.03.10 14:35:44 INFO  Scala CLI:     BuildTargetIdentifier [
2024.03.10 14:35:44 INFO  Scala CLI:       uri = "file:/home/runner/work/metals/metals/tests/unit/target/e2e/file-watcher/didChangeWatchedFiles-notification/.scala-build/?id=didChangeWatchedFiles-notification_f4dd477a3a-test"
2024.03.10 14:35:44 INFO  Scala CLI:     ]
2024.03.10 14:35:44 INFO  Scala CLI:   )
2024.03.10 14:35:44 INFO  Scala CLI: ]. Shutting down the server:
2024.03.10 14:35:44 INFO  Scala CLI:  org.eclipse.lsp4j.jsonrpc.MessageIssueException: Message could not be parsed.
2024.03.10 14:35:44 INFO  Scala CLI: 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponseIssues(RemoteEndpoint.java:358)
2024.03.10 14:35:44 INFO  Scala CLI: 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handle(RemoteEndpoint.java:317)
2024.03.10 14:35:44 INFO  Scala CLI: 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:198)
2024.03.10 14:35:44 INFO  Scala CLI: 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
2024.03.10 14:35:44 INFO  Scala CLI: 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
2024.03.10 14:35:44 INFO  Scala CLI: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2024.03.10 14:35:44 INFO  Scala CLI: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024.03.10 14:35:44 INFO  Scala CLI: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024.03.10 14:35:44 INFO  Scala CLI: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024.03.10 14:35:44 INFO  Scala CLI: 	at java.base/java.lang.Thread.run(Thread.java:840)
2024.03.10 14:35:44 INFO  Scala CLI: 
```

**To Reproduce**
Try to send dependencyModules request, connected to https://github.com/scalameta/metals/pull/6213

It's wrongly set to true in https://github.com/VirtusLab/scala-cli/blob/22fe1aad7808f58cfd17c9a139a19a5135603aa5/modules/build/src/main/scala/scala/build/bsp/BspServer.scala#L176

**Expected behaviour**
dependencyModulesProvider is set to true only if underlying Bloop supports it.

**Comment by fthomas** [comment]
This is somewhat related to this issue. Bloop supports `dependencyModules` since https://github.com/scalacenter/bloop/pull/2197. Is there some ETA when this will be available in Scala CLI?

**Comment by tgodzik** [comment]
Alex fixed the release, so I will port that over for now (I need to reabsorb the fork at some point)

**Comment by tgodzik** [comment]
I am running the release in https://github.com/scala-cli/bloop-core/actions/runs/8457371951, once it's out we'll bump bloop in Scala CLI and do a release.

**Comment by tgodzik** [comment]
Closed by https://github.com/VirtusLab/scala-cli/pull/2818
