### ISSUE TITLE
Bloop `libdaemonjvm.server.LockError$ZombieFound` when Coursier cache is in an inconsistent state

### ISSUE THREAD

**Issue by kavedaa** [VirtusLab/scala-cli#2899]
**Version(s)**

```
>scala-cli --version
Scala CLI version: 1.3.1
Scala version (default): 3.4.1
```

**Describe the bug**

When attempting to compile a .scala file using scala-cli, it fails with `Error: bloop.rifle.FailedToStartServerExitCodeException: Server failed with exit code 1`

**To Reproduce**

test.scala:

```
@main def hello() = println("Hello world")
```

Run:

`scala-cli test.scala`

Output:

```
Starting compilation server
Error: bloop.rifle.FailedToStartServerExitCodeException: Server failed with exit code 1
For more details, please see 'E:\prog\scala\2024-05-09\.scala-build\stacktraces\1715261914-11874568566794901524.log'
Running
  C:\Program Files\scala-cli-x86_64-pc-win32\scala-cli.exe --power bloop output
might give more details.
```

Log file:

```
bloop.rifle.FailedToStartServerExitCodeException: Server failed with exit code 1
  bloop.rifle.internal.Operations$.$anonfun$startServer$8(Operations.scala:264)
  bloop.rifle.BloopRifleLogger.$anonfun$runnable$1(BloopRifleLogger.scala:14)
  java.base@17.0.6/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
  java.base@17.0.6/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
  java.base@17.0.6/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
  java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  java.base@17.0.6/java.lang.Thread.run(Thread.java:833)
  com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
  com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:178)
```

Output of `scala-cli.exe --power bloop output`:

```
>scala-cli --power bloop output
Bloop server PID: 25616
Ignoring SIGINT
Will truncate output file C:\Users\Knut Arne Vedaa\AppData\Local\ScalaCli\data\bloop\daemon\output every 5 minutes
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 2696, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 2696, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 2696, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 2696, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 2696, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 2696, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 2696, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 2696, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 2696, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 2696, trying again in 3 seconds
Exception in thread "main" java.lang.Exception: libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 2696
        at bloop.Bloop$.loop$1(Bloop.scala:102)
        at bloop.Bloop$.main(Bloop.scala:114)
        at bloop.Bloop.main(Bloop.scala)
Caused by: libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 2696
        at libdaemonjvm.server.Lock$.ifProcessRunning$1(Lock.scala:59)
        at libdaemonjvm.server.Lock$.$anonfun$tryAcquire$6(Lock.scala:76)
        at libdaemonjvm.server.Lock$.$anonfun$tryAcquire$6$adapted(Lock.scala:75)
        at scala.Option.flatMap(Option.scala:271)
        at libdaemonjvm.server.Lock$.ifFiles$1(Lock.scala:75)
        at libdaemonjvm.server.Lock$.tryAcquire(Lock.scala:94)
        at bloop.Bloop$.loop$1(Bloop.scala:93)
        ... 2 more
Caused by: java.net.ConnectException: Connection refused: connect
        at java.base/sun.nio.ch.UnixDomainSockets.connect0(Native Method)
        at java.base/sun.nio.ch.UnixDomainSockets.connect(UnixDomainSockets.java:148)
        at java.base/sun.nio.ch.UnixDomainSockets.connect(UnixDomainSockets.java:144)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:851)
        at libdaemonjvm.internal.Java16SocketHandler$.client(Java16SocketHandler.scala:22)
        at libdaemonjvm.internal.SocketHandler$.client(SocketHandler.scala:18)
        at libdaemonjvm.internal.SocketFile$.connect(SocketFile.scala:23)
        at libdaemonjvm.internal.SocketFile$.canConnect(SocketFile.scala:14)
        at libdaemonjvm.server.Lock$.ifProcessRunning$1(Lock.scala:57)
        ... 8 more
```

**Expected behaviour**

That the file is compiled and run.

**Comment by Gedochao** [comment]
This is a known problem with Bloop. You likely have some inconsistent state in your Coursier cache.
To fix this, make sure to:
- purge your local Coursier cache: https://get-coursier.io/docs/cache
- `scala-cli clean .`
- if this still doesn't help, try also purging C:\Users\Knut Arne Vedaa\AppData\Local\ScalaCli\data\bloop\daemon

If everything else fails, please try to provide us the outputs under increased verbosity with `-v -v -v`
```bash
scala-cli test.scala -v -v -v
```

If you're desparate to make your build work and the above steps did not help, you can also run Scala CLI with Bloop turned off by using `--server=false`. This should solve the problem for you, although building without Bloop is considerably slower.
```bash
scala-cli test.scala --server=false
```

**Comment by kavedaa** [comment]
I can confirm that purging the cache solved the issue. The other steps were not necessary.

**Comment by Gedochao** [comment]
I'll leave this open, as we don't seem to have any other ticket to track this particular issue.
The steps for the workaround are known, but optimally we should find a way to recover from this problem when it occurs.

**Comment by lrytz** [comment]
This is probably a duplicate of https://github.com/VirtusLab/scala-cli/issues/2451

**Comment by mpkocher** [comment]
This is a really cryptic error when this occurs. 

Also, depending on how you nuke your Coursier cache, you might have to recreate your env/setup from scratch.

**Comment by tgodzik** [comment]
This should be fixed in the newest Bloop and Scala CLI. Might be worth posting the logs again to see what is going on.

**Comment by Gedochao** [comment]
@mpkocher is this still occurring for you? are you using the newest Scala CLI + Bloop? 
If so, let us know, we'll try to reproduce it.

**Comment by SethTisue** [comment]
For a long time I used to get this regularly in the Scala 2 community build, but now I don't recall having seen it in ages. I think we could probably close this ticket at this point?

**Comment by Gedochao** [comment]
Closing, if you run into it again, please open a new issue (but possibly link back here).
