### ISSUE TITLE
Exception stacktrace on running file that doesn't exist

### ISSUE THREAD

**Issue by pikinier20** [VirtusLab/scala-cli#313]
Scala CLI version 0.0.7
Assuming that file `foo.sc` doesn't exists, running `scala-cli run foo.sc` we get:
```
Exception in thread "main" java.nio.file.NoSuchFileException: .../foo.sc
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.nio.file.Files.newByteChannel(Files.java:371)
        at java.nio.file.Files.newByteChannel(Files.java:422)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
        at java.nio.file.Files.newInputStream(Files.java:156)
        at os.Path.getInputStream(Path.scala:475)
        at os.read$bytes$.apply(ReadWriteOps.scala:256)
        at os.read$.apply(ReadWriteOps.scala:216)
        ...
        at scala.build.Build$.build(Build.scala:371)
        at scala.cli.commands.Run$.run(Run.scala:71)
        at scala.cli.commands.Run$.run(Run.scala:20)
        at scala.cli.commands.Run$.run(Run.scala:14)
        at caseapp.core.app.CaseApp.main(CaseApp.scala:150)
        at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:112)
        at scala.cli.ScalaCli$.main(ScalaCli.scala:97)
        at scala.cli.ScalaCli.main(ScalaCli.scala)
```

Expected behavior would be to report some prettier error

**Comment by Skamandrios42** [comment]
This does still happen in version 0.0.9 if the file extension is .sc:
~~~
 > scala-cli version
0.0.9
 > scala-cli run DoesNotExist.sc
Exception in thread "main" java.nio.file.NoSuchFileException: .../DoesNotExist.sc
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.nio.file.Files.newByteChannel(Files.java:371)
	at java.nio.file.Files.newByteChannel(Files.java:422)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
          [...]
	at scala.build.Build$.build(Build.scala:352)
	at scala.build.Build$.build(Build.scala:376)
	at scala.cli.commands.Run$.run(Run.scala:83)
	at scala.cli.commands.Run$.run(Run.scala:24)
	at scala.cli.commands.Run$.run(Run.scala:14)
	at caseapp.core.app.CaseApp.main(CaseApp.scala:149)
	at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:114)
	at scala.cli.ScalaCli$.main(ScalaCli.scala:99)
	at scala.cli.ScalaCli.main(ScalaCli.scala)
 > 
~~~
I would suggest to reopen the issue.
