### ISSUE TITLE
TASTy signature has wrong version error

### ISSUE THREAD

**Issue by ckipp01** [VirtusLab/scala-cli#325]
Ideally, I don't think this should really ever surface to the user. For example, a minified version of a script I have is currently causing this:

```scala
// using scala 3
import $dep.`com.lihaoyi::requests:0.6.9`

object LatestVersion extends App {

  val metadataLoc = ""
  val creds = ""

  val existingResponse = requests.get(
    metadataLoc,
    headers = Map(
      "Authorization" -> s"Basic: $creds"
    )
  )

}
```
And when I try to `scala-cli run <file>` you see the following:

```
❯ scala-cli run Request.scala
Compiling project (Scala 3.1.0, JVM)
Compiled project (Scala 3.1.0, JVM)
error while loading Typeable$package$,
class file scala/reflect/Typeable$package.class is broken, reading aborted with class dotty.tools.tasty.UnpickleException
TASTy signature has wrong version.
 expected: {majorVersion: 28, minorVersion: 0}
 found   : {majorVersion: 28, minorVersion: 1}

This TASTy file was produced by a more recent, forwards incompatible release.
To read this TASTy file, please upgrade your tooling.
The TASTy file was produced by Scala 3.1.0-bin-nonbootstrapped.
error while loading Quotes$package$,
class file scala/quoted/Quotes$package.class is broken, reading aborted with class dotty.tools.tasty.UnpickleException
TASTy signature has wrong version.
 expected: {majorVersion: 28, minorVersion: 0}
 found   : {majorVersion: 28, minorVersion: 1}

This TASTy file was produced by a more recent, forwards incompatible release.
To read this TASTy file, please upgrade your tooling.
The TASTy file was produced by Scala 3.1.0-bin-nonbootstrapped.
error while loading Expr$,
class file scala/quoted/runtime/Expr.class is broken, reading aborted with class dotty.tools.tasty.UnpickleException
TASTy signature has wrong version.
 expected: {majorVersion: 28, minorVersion: 0}
 found   : {majorVersion: 28, minorVersion: 1}

This TASTy file was produced by a more recent, forwards incompatible release.
To read this TASTy file, please upgrade your tooling.
The TASTy file was produced by Scala 3.1.0-bin-nonbootstrapped.
object Expr does not have a member method quote while compiling /var/folders/fq/nx_jsnyd6550xp03czx898d40000gn/T/runner_3.jar_sources3990067349970980520/scala/cli/runner/Stacktrace.tasty
Exception in thread "main" dotty.tools.dotc.core.TypeError: object Expr does not have a member method quote
        at dotty.tools.dotc.core.Denotations$Denotation.requiredSymbol(Denotations.scala:306)
        at dotty.tools.dotc.core.Denotations$Denotation.requiredMethod(Denotations.scala:313)
        at dotty.tools.dotc.core.Definitions.QuotedRuntime_exprQuote(Definitions.scala:797)
        at dotty.tools.dotc.transform.SymUtils$.isQuote(SymUtils.scala:237)
        at dotty.tools.dotc.CompilationUnit$Force.traverse(CompilationUnit.scala:139)
        at dotty.tools.dotc.CompilationUnit$.apply(CompilationUnit.scala:107)
        at dotty.tools.dotc.CompilationUnit$.apply(CompilationUnit.scala:98)
        at dotty.tools.dotc.fromtasty.ReadTasty.compilationUnit$1(ReadTasty.scala:42)
        at dotty.tools.dotc.fromtasty.ReadTasty.readTASTY(ReadTasty.scala:70)
        at dotty.tools.dotc.fromtasty.ReadTasty.runOn$$anonfun$1(ReadTasty.scala:25)
        at scala.collection.immutable.List.flatMap(List.scala:293)
        at dotty.tools.dotc.fromtasty.ReadTasty.runOn(ReadTasty.scala:25)
        at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
        at dotty.tools.dotc.Run.runPhases$5(Run.scala:215)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:223)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:230)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:172)
        at dotty.tools.dotc.fromtasty.TASTYRun.compile(TASTYRun.scala:11)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
        at dotty.tools.dotc.Driver.process(Driver.scala:199)
        at dotty.tools.dotc.Driver.process(Driver.scala:167)
        at dotty.tools.dotc.Driver.process(Driver.scala:179)
        at scala.tasty.inspector.TastyInspector$.inspectFiles(TastyInspector.scala:103)
        at scala.tasty.inspector.TastyInspector$.inspectAllTastyFiles(TastyInspector.scala:52)
        at scala.tasty.inspector.TastyInspector$.inspectTastyFiles(TastyInspector.scala:27)
        at org.virtuslab.stacktraces.core.StacktracesInspector$.inspectStackTrace(StacktracesInspector.scala:25)
        at scala.cli.runner.Stacktraces$.$anonfun$1(Stacktraces.scala:28)
        at scala.collection.immutable.List.flatMap(List.scala:293)
        at scala.cli.runner.Stacktraces$.convertToPrettyStackTrace(Stacktraces.scala:37)
        at scala.cli.runner.Stacktrace$.print(Stacktrace.scala:14)
        at scala.cli.runner.StackTracePrinter.printException(StackTracePrinter.scala:91)
        at scala.cli.runner.Runner$.main(Runner.scala:22)
        at scala.cli.runner.Runner.main(Runner.scala)
```

I'd wager that a user won't have any clue what this error means. To be honest, I don't even understand how there is a mismatch here and I'm also unsure where `3.1.0-bin-nonbootstrapped` is actually coming from.

**Comment by ckipp01** [comment]
One other note on this since I'm running into this a lot today. In certain situations that only happens when there is a runtime error and it actually takes away from seeing the error. Notice in this example it spits out a bunch of info about TASTy which takes away from the actual error message on the bottom:

```
❯ scala-cli run . -- test
Failed to process exception, failure:dotty.tools.tasty.UnpickleException: TASTy signature has wrong version.
 expected: {majorVersion: 28, minorVersion: 0}
 found   : {majorVersion: 28, minorVersion: 1}

This TASTy file was produced by a more recent, forwards incompatible release.
To read this TASTy file, please upgrade your tooling.
The TASTy file was produced by Scala 3.1.0.
        at dotty.tools.tasty.TastyHeaderUnpickler.check(TastyHeaderUnpickler.scala:90)
        at dotty.tools.tasty.TastyHeaderUnpickler.readFullHeader(TastyHeaderUnpickler.scala:80)
        at dotty.tools.tasty.TastyHeaderUnpickler.readHeader(TastyHeaderUnpickler.scala:38)
        at dotty.tools.dotc.core.tasty.TastyUnpickler.<init>(TastyUnpickler.scala:89)
        at dotty.tools.dotc.core.tasty.TastyUnpickler.<init>(TastyUnpickler.scala:32)
        at dotty.tools.dotc.core.tasty.TastyClassName.<init>(TastyClassName.scala:19)
        at dotty.tools.dotc.fromtasty.TastyFileUtil$.getClassName(TastyFileUtil.scala:37)
        at dotty.tools.dotc.fromtasty.TastyFileUtil$.getClassPath(TastyFileUtil.scala:19)
        at dotty.tools.dotc.Driver.$anonfun$1(Driver.scala:106)
        at scala.collection.immutable.List.flatMap(List.scala:293)
        at dotty.tools.dotc.Driver.fromTastySetup(Driver.scala:113)
        at dotty.tools.dotc.Driver.setup$$anonfun$1(Driver.scala:90)
        at scala.Option.map(Option.scala:242)
        at dotty.tools.dotc.Driver.setup(Driver.scala:90)
        at dotty.tools.dotc.Driver.process(Driver.scala:197)
        at dotty.tools.dotc.Driver.process(Driver.scala:167)
        at dotty.tools.dotc.Driver.process(Driver.scala:179)
        at scala.tasty.inspector.TastyInspector$.inspectFiles(TastyInspector.scala:103)
        at scala.tasty.inspector.TastyInspector$.inspectAllTastyFiles(TastyInspector.scala:52)
        at scala.tasty.inspector.TastyInspector$.inspectTastyFiles(TastyInspector.scala:27)
        at org.virtuslab.stacktraces.core.StacktracesInspector$.inspectStackTrace(StacktracesInspector.scala:25)
        at scala.cli.runner.Stacktraces$.$anonfun$1(Stacktraces.scala:28)
        at scala.collection.immutable.List.flatMap(List.scala:293)
        at scala.cli.runner.Stacktraces$.convertToPrettyStackTrace(Stacktraces.scala:37)
        at scala.cli.runner.Stacktrace$.liftedTree1$1(Stacktrace.scala:15)
        at scala.cli.runner.Stacktrace$.print(Stacktrace.scala:24)
        at scala.cli.runner.StackTracePrinter.printException(StackTracePrinter.scala:91)
        at scala.cli.runner.Runner$.main(Runner.scala:22)
        at scala.cli.runner.Runner.main(Runner.scala)
----

Exception in thread "main" scala.MatchError: List() (of class scala.collection.immutable.Nil$)
        at Main$package$.fetch$1(Main.scala:24)
        at Main$package$.check(Main.scala:53)
        at Main$package$.exists(Main.scala:68)
        at Main$package$.run(Main.scala:80)
        at run.main(Main.scala:76)
```

**Comment by tpasternak** [comment]
Thank you for reporting. Btw I found the example can be even shorter:

```
// using scala "3.1.0"

object LatestVersion extends App {
  throw new RuntimeException("")
}
```

**Comment by SethTisue** [comment]
I have seen this a few times. (I hadn't reported it because I wanted to try to get some feeling for the circumstances under which it was happening.)

**Comment by tpasternak** [comment]
Yes, we're about to fix it https://github.com/VirtusLab/pretty-stacktraces/issues/18

**Comment by lwronski** [comment]
From the next version of scala-cli 0.1.0, if we fail to print an exception using pretty-stack-traces we'll just skip that and print the exception normally.

Only if, the verbosity is higher than 1, we will print `dotty.tools.tasty.UnpickleException` from `pretty-stack-traces`.  - #506 

We have to wait until pretty-stack-traces will support Scala 3.1, for now we will ignore this exception.

**Comment by lwronski** [comment]
The above exception was thrown from `pretty-stacktraces` which was removed in ScalaCLI `0.1.5`. So, this exception shouldn't occur again.
