### ISSUE TITLE
scala-cli browse/metabrowse fails with download error

### ISSUE THREAD

**Issue by bs76** [VirtusLab/scala-cli#366]
when running `scala-cli browse *.scala` scala-cli fails with download error:

```
~/w/s/abcd ❯❯❯ scala-cli browse --java-home /usr/lib/jvm/java-11-openjdk-amd64 *.scala
Exception in thread "main" coursier.cache.ArtifactError$NotFound: not found: https://github.com/alexarchambault/metabrowse/releases/download/latest/metabrowse-3.0.2-x86_64-pc-linux.gz
        at coursier.cache.internal.Downloader$Blocking$.doDownload(Downloader.scala:233)
        at coursier.cache.internal.Downloader$Blocking$.$anonfun$remote$2(Downloader.scala:414)
        at coursier.cache.internal.Downloader$.$anonfun$downloading$1(Downloader.scala:725)
        at coursier.cache.CacheLocks$.withUrlLock(CacheLocks.scala:118)
        at coursier.cache.internal.Downloader$.helper$2(Downloader.scala:725)
        at coursier.cache.internal.Downloader$.coursier$cache$internal$Downloader$$downloading(Downloader.scala:771)
        at coursier.cache.internal.Downloader$Blocking$.$anonfun$remote$1(Downloader.scala:414)
        at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:71)
        at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:97)
        at coursier.cache.internal.Downloader$Blocking$.remote(Downloader.scala:416)
        at coursier.cache.internal.Downloader.$anonfun$remote$5(Downloader.scala:520)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:567)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
~/w/s/abcd ❯❯❯ 
```

There's no release in the GH repo (none at all)

**Comment by romanowski** [comment]
Hi @bs76 , at this moment metabrowse support is experimental and we are still not sure if we will continue supporting it in future. 

Moreover, it seems that for now, we support only [a set of Scala `2.12` and `2.13` versions
](https://github.com/alexarchambault/metabrowse/releases)

**Comment by bs76** [comment]
Ok, how about hiding it away now, or marking as experimental ? Otherwise it looks like it's not finished.

**Comment by SethTisue** [comment]
Hit this myself today.

Seems like if it's not being maintained it should just be removed, and considered for possible re-addition later.

**Comment by bishabosha** [comment]
I also got a similar error:
```
$ scala-cli browse foo
Compiling project (Scala 2.13.10, JVM)
Compiled project (Scala 2.13.10, JVM)
Error: coursier.error.ResolutionError$CantDownloadModule: Error downloading org.scalameta:metabrowse-server_2.13:2.4.4
  not found: /Users/jamie/.ivy2/local/org.scalameta/metabrowse-server_2.13/2.4.4/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/scalameta/metabrowse-server_2.13/2.4.4/metabrowse-server_2.13-2.4.4.pom
```

**Comment by kubukoz** [comment]
Metabrowse is now gone, shall we close this?
