### ISSUE TITLE
trouble when using setup-ide

### ISSUE THREAD

**Issue by julienrf** [VirtusLab/scala-cli#396]
~~~ scala
// using scala 2.13.6

object Main {
  def main(args: Array[String]): Unit = ()
}
~~~

~~~ text
$ scala-cli setup-ide .
~~~

When importing project in IntelliJ:

~~~ text
Exception in thread "main" java.io.IOException: Cannot run program "/home/julien/.coursier/cache/jvm/graalvm-java11@19.3.1/bin/java" (in directory "/tmp/ide"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at os.proc.proc$lzycompute$1(ProcessOps.scala:128)
	at os.proc.proc$1(ProcessOps.scala:122)
	at os.proc.spawn(ProcessOps.scala:135)
	at os.proc.call(ProcessOps.scala:76)
	at scala.build.options.BuildOptions.javaCommand0$lzycompute(BuildOptions.scala:127)
	at scala.build.options.BuildOptions.javaCommand0(BuildOptions.scala:122)
	at scala.build.options.BuildOptions.javaHome(BuildOptions.scala:171)
	at scala.cli.commands.SharedOptions.bloopRifleConfig(SharedOptions.scala:182)
	at scala.cli.commands.Bsp$.run(Bsp.scala:25)
	at scala.cli.commands.Bsp$.run(Bsp.scala:12)
	at caseapp.core.app.CaseApp.main(CaseApp.scala:150)
	at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:112)
	at scala.cli.ScalaCli$.main(ScalaCli.scala:98)
	at scala.cli.ScalaCli.main(ScalaCli.scala)
Caused by: java.io.IOException: error=2, No such file or directory
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_io_IOException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
	at java.lang.ProcessImpl.forkAndExec(ProcessImpl.java)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 15 more
~~~

Not sure it works better in Metals. The import when fine and I could get auto-completion. However, nothing happens if I try to run the project from Metals.

Please let me know if you need additional details from me.

**Comment by lwronski** [comment]
@julienrf Thanks for reporting, which version of ScalaCLI are you using?  It should work with `0.0.8` version.

After clicking run `button` in VSCode, it should open `Debug Console ` with the output of running app.

**Comment by julienrf** [comment]
Sorry, I forgot to indicate that. I am using 0.0.8.

**Comment by lwronski** [comment]
1. Can you attach logs from Metals? There are any errors? Logs from Metals you can find in `.metals/metals.log` file.
2. Does the `DebugConsole` window appear when you click `run` button?

IntelliJ  - For now, we don't recommend using IntelliJ with ScalaCLI project, it's still under development. I will keep this issue open until we add support for Intellij.

**Comment by julienrf** [comment]
Thank you for your help!

Yes, DebugConsole window appears when I click `run`. Actually, when trying to reproduce the issue, I noticed that the program eventually runs, but 15 seconds after I click `run`. Maybe this was also the case when I filled the issue, but I was just not patient enough to see the output…

BTW, I find it surprising that you have to implement special support for Metals or IntelliJ. I believe the goal of BSP is precisely to allow editors to compile, build, and run projects without specific support. Or, maybe the problem is that BSP integration is not good enough in Metals or IntelliJ? Why do we have to add special support for one IDE or the other?

I think we can close the issue, unless you see something actionable?

**Comment by lwronski** [comment]
Yes, IntelliJ need special support for ScalaCLI project structure, for example:

- IntelliJ currently does not automatically pick up changes in the project structure, so any change in dependencies, compiler options, etc., need to be manually reloaded.
- IntelliJ requires, that source files must be placed within a directory, it doesn't work with simple scala-cli project with one file at the top.
- IntelliJ doesn't automatically pick-up Scala version from project bloop setting
