### ISSUE TITLE
Artifact not found when browse scala code

### ISSUE THREAD

**Issue by vitojeng** [VirtusLab/scala-cli#399]
Artifact not found:
https://github.com/alexarchambault/metabrowse/releases/download/latest/metabrowse-3.0.2-x86_64-apple-darwin.gz

Full stacktrace is here:

```
$ scala-cli browse .
Exception in thread "main" coursier.cache.ArtifactError$NotFound: not found: https://github.com/alexarchambault/metabrowse/releases/download/latest/metabrowse-3.0.2-x86_64-apple-darwin.gz
	at coursier.cache.internal.Downloader$Blocking$.doDownload(Downloader.scala:233)
	at coursier.cache.internal.Downloader$Blocking$.$anonfun$remote$2(Downloader.scala:414)
	at coursier.cache.internal.Downloader$.$anonfun$downloading$1(Downloader.scala:725)
	at coursier.cache.CacheLocks$.withUrlLock(CacheLocks.scala:118)
	at coursier.cache.internal.Downloader$.helper$2(Downloader.scala:725)
	at coursier.cache.internal.Downloader$.coursier$cache$internal$Downloader$$downloading(Downloader.scala:771)
	at coursier.cache.internal.Downloader$Blocking$.$anonfun$remote$1(Downloader.scala:414)
	at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:71)
	at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:97)
	at coursier.cache.internal.Downloader$Blocking$.remote(Downloader.scala:416)
	at coursier.cache.internal.Downloader.$anonfun$remote$5(Downloader.scala:520)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:567)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```

**Comment by vitojeng** [comment]
duplicate with #366
