### ISSUE TITLE
No diagnostics via BSP in case of wrong using directives

### ISSUE THREAD

**Issue by tgodzik** [VirtusLab/scala-cli#459]
Recently `resource` was renamed to `resourceDir` and now when for example using a snippet:
```scala
// using resource "./resources"
// using lib com.lihaoyi::pprint:0.6.6
// using lib org.scala-lang.modules::scala-parallel-collections:1.0.4

@main
def main = println("Hello world!")
```

we get in Metals:
```
2021.12.07 11:18:38 ERROR Timeout waiting for 'build/initialize' response
2021.12.07 11:18:38 WARN  Retrying connection to the build server scala-cli
2021.12.07 11:18:38 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/tgodzik/.cache/metals/bsp.trace.json
```

It's very confusing for users since there is nothing to indicate what the error is.

**Comment by tpasternak** [comment]
Interesting, scala-cli hangs and prints 
```
Exception in thread "main" java.lang.ClassCastException: class scala.build.errors.UnusedDirectiveError cannot be cast to class scala.Tuple2 (scala.build.errors.UnusedDirectiveError and scala.Tuple2 are in unnamed module of loader java.net.URLClassLoader @2f2c9b19)
	at scala.build.bsp.BspImpl.run(BspImpl.scala:377)
	at scala.cli.commands.Bsp$.$anonfun$run$3(Bsp.scala:48)
	at scala.cli.commands.Bsp$.$anonfun$run$3$adapted(Bsp.scala:35)
	at scala.build.bsp.BspThreads$.withThreads(BspThreads.scala:23)
	at scala.cli.commands.Bsp$.run(Bsp.scala:35)
	at scala.cli.commands.Bsp$.run(Bsp.scala:12)
	at caseapp.core.app.CaseApp.main(CaseApp.scala:149)
	at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:114)
	at scala.cli.ScalaCli$.main(ScalaCli.scala:99)
	at scala.cli.ScalaCli.main(ScalaCli.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at coursier.bootstrap.launcher.a.a(Unknown Source)
	at coursier.bootstrap.launcher.Launcher.main(Unknown Source)

```

**Comment by tpasternak** [comment]
~Done on scala-cli site (we print bloop's stderr by default). Probably would require changes in bloop and dotty as well..~
