### ISSUE TITLE
JVM Launcher does not work

### ISSUE THREAD

**Issue by tpasternak** [VirtusLab/scala-cli#541]
On 7d3144dd9969935e1238f1e109298f3d3c1f831d 

Steps:
1. ` ./mill -i cli.launcher`
2. `./out/cli/launcher/dest/launcher package --standalone examples/scala-files -o scalaFiles1`

Expected:
Package is built

Actual:
```
Exception in thread "main" java.util.concurrent.TimeoutException: Futures timed out after [30 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:223)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
	at scala.concurrent.Await$.result(package.scala:146)
	at scala.build.bloop.BloopServer$.startBloop$1(BloopServer.scala:80)
	at scala.build.bloop.BloopServer$.ensureBloopRunning(BloopServer.scala:109)
	at scala.build.bloop.BloopServer$.bsp(BloopServer.scala:153)
	at scala.build.bloop.BloopServer$.buildServer(BloopServer.scala:183)
	at scala.build.bloop.BloopServer$.withBuildServer(BloopServer.scala:248)
	at scala.build.Build$.build(Build.scala:377)
	at scala.build.Build$.build(Build.scala:401)
	at scala.cli.commands.Package$.run(Package.scala:72)
	at scala.cli.commands.Package$.run(Package.scala:31)
	at caseapp.core.app.CaseApp.main(CaseApp.scala:149)
	at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:116)
	at scala.cli.ScalaCli$.main0(ScalaCli.scala:173)
	at scala.cli.ScalaCli$.main(ScalaCli.scala:114)
	at scala.cli.ScalaCli.main(ScalaCli.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at coursier.bootstrap.launcher.a.a(Unknown Source)
	at coursier.bootstrap.launcher.Launcher.main(Unknown Source)

```

**Comment by tpasternak** [comment]
https://github.com/VirtusLab/scala-cli/runs/4804289995?check_suite_focus=true#step:7:622

**Comment by tpasternak** [comment]
Seems to be a problem only on GH Actions
