### ISSUE TITLE
Self-started bloop server doesn't start

### ISSUE THREAD

**Issue by kubukoz** [VirtusLab/scala-cli#599]
**Version(s)**

0.1.0, x86 mac binary downloaded from releases tab.

**Describe the bug**

`scala-cli bloop start` fails every time. However, trying to compile some sources successfully starts bloop.

<details>
<summary>Stack trace</summary>

```
java.lang.Exception: Server didn't start
  scala.build.blooprifle.internal.Operations$.$anonfun$startServer$2(Operations.scala:153)
  scala.build.blooprifle.BloopRifleLogger.$anonfun$runnable$1(BloopRifleLogger.scala:12)
  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
  java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
  java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  java.lang.Thread.run(Thread.java:833)
  com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
  com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
```

</details>

**To Reproduce**

1. Install scala-cli
2. `scala-cli bloop start`
3. profit

**Expected behaviour**
A server starts just like when running a build :)

**Comment by alexarchambault** [comment]
I didn't check the Scala CLI sources yet, but it seems `scala-cli bloop start` tries to use the system JVM to start Bloop. Locally, with Java 11 as system JVM, it says:
```text
$ java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

$ scala-cli bloop start -v -v -v -v
…
Error: VM option 'UseZGC' is experimental and must be enabled via -XX:+UnlockExperimentalVMOptions.
Error: The unlock option must precede 'UseZGC'.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
…
```

while the following works for me:
```text
$ eval "$(cs java --env --jvm temurin:17)"
$ java -version
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Temurin-17+35 (build 17+35)
OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)

$ scala-cli bloop start
Bloop server started.
```

I guess we should ensure that our JVM 17 is used by default by `scala-cli bloop start` too (as is the case when the other commands start Bloop).

@kubukoz What does `java -version` says on your system?

**Comment by kubukoz** [comment]
```
openjdk version "11.0.11" 2021-04-20 LTS
OpenJDK Runtime Environment Zulu11.48+21-CA (build 11.0.11+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.48+21-CA (build 11.0.11+9-LTS, mixed mode)
```

Ideally `JAVA_HOME` or whatever is in the PATH of the `scala-cli` binary would be used, this way I can scope the usage of a JVM 17 for scala-cli's usage only.

**Comment by keynmol** [comment]
I'm having the same problem on Apple M1.

And I agree with @kubukoz - I already run Java 17 natively built for arm64, and I wish scala-cli would just use that.

```
velvetbaldmime@Antons-Air /v/f/m/d/T/tmp.plBHFF7i> java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode)

velvetbaldmime@Antons-Air /v/f/m/d/T/tmp.plBHFF7i> scala-cli --version
0.1.0
velvetbaldmime@Antons-Air /v/f/m/d/T/tmp.plBHFF7i> scala-cli test.scala
Bloop daemon status: not running
Starting Bloop 1.4.19 at /Users/velvetbaldmime/Library/Caches/ScalaCli/bloop/daemon using JVM /Users/velvetbaldmime/Library/Caches/Coursier/arc/https/github.com/adoptium/temurin17-binaries/releases/download/jdk-17%252B35/OpenJDK17-jdk_x64_mac_hotspot_17_35.tar.gz/jdk-17+35/Contents/Home/bin/java
Error: java.lang.Exception: Server didn't start
For more details, please see '/private/var/folders/my/drt5584s2w59ncgxgxpq7v040000gn/T/tmp.plBHFF7i/.scala-build/stacktraces/1643998345-954539311384192108.log
```

Currently I can't find a way to use 0.1.0 so I dropped it down to 0.0.9

It's particularly important on M1 because I don't want compilation to run through emulator - and scala-cli will see `os.arch` as x86 if the binary is running under rosetta.

**Comment by alexarchambault** [comment]
@keynmol When using standard commands, `--bloop-jvm` should work, so something like this should run fine on M1:
```text
$ scala-cli --bloop-jvm system test.scala
```

**Comment by alexarchambault** [comment]
Seems we need to handle the architecture more carefully though… (and also default to the system JVM when it's at least Java 17)

**Comment by SethTisue** [comment]
Related: https://github.com/coursier/coursier/issues/2335

**Comment by keynmol** [comment]
@alexarchambault nope, seems like the same issue:

```
velvetbaldmime@Antons-Air /v/f/m/d/T/tmp.YhCQZV6k [1]> scala-cli --bloop-jvm system test.scala
Bloop daemon status: not running
Starting Bloop 1.4.19 at /Users/velvetbaldmime/Library/Caches/ScalaCli/bloop/daemon using JVM /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java
Error: java.lang.Exception: Server didn't start
For more details, please see '/private/var/folders/my/drt5584s2w59ncgxgxpq7v040000gn/T/tmp.YhCQZV6k/.scala-build/stacktraces/1644836015-15645112221190994336.log'
```

**Comment by alexarchambault** [comment]
@keynmol At least it tries to use _your_ JVM 😅

Can you run the same command with `-v -v -v -v`, and paste the output here?

**Comment by keynmol** [comment]
Haha, you are right! I didn't notice and was too quick to post a rebuttal :P 

After a lot of jars:

```
Checking for a running Bloop server at /Users/velvetbaldmime/Library/Caches/ScalaCli/bloop/daemon ...
Attempting to connect to Bloop server /Users/velvetbaldmime/Library/Caches/ScalaCli/bloop/daemon ...
Connection attempt result: None
Error occurred during initialization of VM
Multiple garbage collectors selected
Exception in thread "main" java.lang.Exception: Server didn't start
	at scala.build.blooprifle.internal.Operations$.$anonfun$startServer$2(Operations.scala:153)
	at scala.build.blooprifle.BloopRifleLogger.$anonfun$runnable$1(BloopRifleLogger.scala:12)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
```

which led me to my custom bloop config in `~/.bloop/bloop.json`: 

```
...
"javaOptions": ["-Xmx4G", "-XX:+UseShenandoahGC"]
...
```

After I removed that option it ran fine.

I feel like when using "system" bloop scala-cli should respect user's GC settings.

**Comment by kubukoz** [comment]
`--bloop-jvm system` works for me, but it'd obviously be great if it wasn't required. Can scala-cli just check if there's a JDK17+ compatible jvm on its `PATH` and use just that?

**Comment by julienrf** [comment]
Hello, I am facing a similar issue. I am not sure what I should do.

Here is the output of `scala-cli run -v -v -v -v my-script.sc`:

~~~ text
Exception in thread "main" java.lang.Exception: libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905
        at bloop.Bloop$.loop$1(Bloop.scala:104)
        at bloop.Bloop$.main(Bloop.scala:113)
        at bloop.Bloop.main(Bloop.scala)
Caused by: libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905
        at libdaemonjvm.server.Lock$.ifProcessRunning$1(Lock.scala:59)
        at libdaemonjvm.server.Lock$.$anonfun$tryAcquire$6(Lock.scala:76)
        at libdaemonjvm.server.Lock$.$anonfun$tryAcquire$6$adapted(Lock.scala:75)
        at scala.Option.flatMap(Option.scala:271)
        at libdaemonjvm.server.Lock$.ifFiles$1(Lock.scala:75)
        at libdaemonjvm.server.Lock$.tryAcquire(Lock.scala:94)
        at bloop.Bloop$.loop$1(Bloop.scala:95)
        ... 2 more
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.UnixDomainSockets.connect0(Native Method)
        at java.base/sun.nio.ch.UnixDomainSockets.connect(UnixDomainSockets.java:148)
        at java.base/sun.nio.ch.UnixDomainSockets.connect(UnixDomainSockets.java:144)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:851)
        at libdaemonjvm.internal.Java16SocketHandler$.client(Java16SocketHandler.scala:22)
        at libdaemonjvm.internal.SocketHandler$.client(SocketHandler.scala:18)
        at libdaemonjvm.internal.SocketFile$.connect(SocketFile.scala:23)
        at libdaemonjvm.internal.SocketFile$.canConnect(SocketFile.scala:14)
        at libdaemonjvm.server.Lock$.ifProcessRunning$1(Lock.scala:57)
        ... 8 more
Checking for a running Bloop server at /home/julien/.local/share/scalacli/bloop/daemon ...
Attempting to connect to Bloop server /home/julien/.local/share/scalacli/bloop/daemon ...
Connection attempt result: None
Bloop server exited with code 1
Running
  scala-cli bloop output
might give more details.
Exception in thread "main" scala.build.blooprifle.FailedToStartServerExitCodeException: Server failed with exit code 1
        at scala.build.blooprifle.internal.Operations$.check0$1$$anonfun$1(Operations.scala:250)
        at scala.build.blooprifle.BloopRifleLogger.runnable$$anonfun$1(BloopRifleLogger.scala:14)
        at java.base@17.0.5/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base@17.0.5/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base@17.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
~~~

Then, `scala-cli --power bloop output` gives the following (which I am not sure how to interpret):

~~~ text
[0.001s][warning][gc,jvmci] Setting EnableJVMCI to false as selected GC does not support JVMCI: z gc
Bloop server PID: 15304
Ignoring SIGINT
Will truncate output file /home/julien/.local/share/scalacli/bloop/daemon/output every 5 minutes
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905, trying again in 3 seconds
Caught libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905, trying again in 3 seconds
Exception in thread "main" java.lang.Exception: libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905
        at bloop.Bloop$.loop$1(Bloop.scala:104)
        at bloop.Bloop$.main(Bloop.scala:113)
        at bloop.Bloop.main(Bloop.scala)
Caused by: libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905
        at libdaemonjvm.server.Lock$.ifProcessRunning$1(Lock.scala:59)
        at libdaemonjvm.server.Lock$.$anonfun$tryAcquire$6(Lock.scala:76)
        at libdaemonjvm.server.Lock$.$anonfun$tryAcquire$6$adapted(Lock.scala:75)
        at scala.Option.flatMap(Option.scala:271)
        at libdaemonjvm.server.Lock$.ifFiles$1(Lock.scala:75)
        at libdaemonjvm.server.Lock$.tryAcquire(Lock.scala:94)
        at bloop.Bloop$.loop$1(Bloop.scala:95)
        ... 2 more
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.UnixDomainSockets.connect0(Native Method)
        at java.base/sun.nio.ch.UnixDomainSockets.connect(UnixDomainSockets.java:148)
        at java.base/sun.nio.ch.UnixDomainSockets.connect(UnixDomainSockets.java:144)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:851)
        at libdaemonjvm.internal.Java16SocketHandler$.client(Java16SocketHandler.scala:22)
        at libdaemonjvm.internal.SocketHandler$.client(SocketHandler.scala:18)
        at libdaemonjvm.internal.SocketFile$.connect(SocketFile.scala:23)
        at libdaemonjvm.internal.SocketFile$.canConnect(SocketFile.scala:14)
        at libdaemonjvm.server.Lock$.ifProcessRunning$1(Lock.scala:57)
        ... 8 more
~~~

**Comment by Gedochao** [comment]
I believe I've encountered it before... no idea how to replicate it though 🤔 

However...
```
Caused by: libdaemonjvm.server.LockError$ZombieFound: Cannot connect to process 1905
```
@julienrf have you tried killing that process? I believe it fixed it for me in the past.
```bash
kill -9 1905
```

If it's recurring, please open a separate ticket so we can track it, I think it may be a separate issue 😅

**Comment by julienrf** [comment]
The process that had the PID 1905 was the NFS server. For the record, I did a `systemctl restart nfs-server.service` that fixed the issue.

However, I believe it would be great to improve the error reporting.

**Comment by julienrf** [comment]
I created #2044 to track that.
