### ISSUE TITLE
Futures timed out

### ISSUE THREAD

**Issue by anatoliykmetyuk** [VirtusLab/scala-cli#776]
**Version(s)**

0.1.2

**Describe the bug**

When I run the following script:

```scala
//> using scala "3.1.1"
println("Foo")
```

Scala-cli says:

```
Error: java.util.concurrent.TimeoutException: Futures timed out after [30 seconds]
For more details, please see '.../.scala-build/stacktraces/1647271220-11054415855645911909.log'
```

The stack trace from the log file:

```
java.util.concurrent.TimeoutException: Futures timed out after [30 seconds]
  scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
  scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
  scala.concurrent.Await$.$anonfun$result$1(package.scala:223)
  scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
  scala.concurrent.Await$.result(package.scala:146)
  scala.build.blooprifle.internal.Operations$.timeout(Operations.scala:384)
  scala.build.blooprifle.internal.Operations$.about(Operations.scala:352)
  scala.build.blooprifle.BloopRifle$.getCurrentBloopVersion(BloopRifle.scala:192)
  scala.build.bloop.BloopServer$.ensureBloopRunning(BloopServer.scala:85)
  scala.build.bloop.BloopServer$.bsp(BloopServer.scala:153)
  scala.build.bloop.BloopServer$.buildServer(BloopServer.scala:183)
  scala.build.bloop.BloopServer$.withBuildServer(BloopServer.scala:248)
  scala.build.Build$.build(Build.scala:408)
  scala.build.Build$.build(Build.scala:432)
  scala.cli.commands.Run$.run(Run.scala:87)
  scala.cli.commands.Run$.run(Run.scala:25)
  scala.cli.commands.Default.run(Default.scala:38)
  scala.cli.commands.Default.run(Default.scala:10)
  caseapp.core.app.CaseApp.main(CaseApp.scala:149)
  caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:116)
  scala.cli.ScalaCliCommands.main(ScalaCliCommands.scala:89)
  scala.cli.ScalaCli$.main0(ScalaCli.scala:148)
  scala.cli.ScalaCli$.main(ScalaCli.scala:71)
  scala.cli.ScalaCli.main(ScalaCli.scala)
```

**To Reproduce**

No idea, probably some intricate state somewhere in the machine is affecting Bloop?

**Expected behaviour**
Should work.

**Comment by lwronski** [comment]
Hi @anatoliykmetyuk,
Can you attach logs from scala-cli with increased verbosity? so, you have to run `scala-cli` in this way:

```
scala-cli hello.scala -v -v -v
```

**Comment by anatoliykmetyuk** [comment]
I rebooted my computer and the problem went away, can't reproduce it anymore... I'll run it with three `-v` next time I see it.

**Comment by anatoliykmetyuk** [comment]
Spotted the problem again, on `0.1.2`. Ran with `-v  -v -v`, got the following:

```
Checking for a running Bloop server at /Users/kmetiuk/Library/Caches/ScalaCli/bloop/daemon ...
Attempting to connect to Bloop server /Users/kmetiuk/Library/Caches/ScalaCli/bloop/daemon ...
Connection attempt result: Some(Right(Right(java.nio.channels.SocketChannel[connected local= remote=/Users/kmetiuk/Library/Caches/ScalaCli/bloop/daemon/socket])))
nailgun debug: Sending arguments '' to Nailgun server
nailgun debug: Sending environment variables to Nailgun server
nailgun debug: Sending working directory /Users/kmetiuk/Projects/simple-rockets-compiler/examples to Nailgun server
nailgun debug: Sending command to about Nailgun server
nailgun debug: Finished sending command information to Nailgun server
nailgun debug: Starting thread to read stdin...
Exception in thread "main" java.util.concurrent.TimeoutException: Futures timed out after [30 seconds]
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
        at scala.concurrent.Await$.$anonfun$result$1(package.scala:223)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
        at scala.concurrent.Await$.result(package.scala:146)
        at scala.build.blooprifle.internal.Operations$.timeout(Operations.scala:373)
        at scala.build.blooprifle.internal.Operations$.about(Operations.scala:341)
        at scala.build.blooprifle.BloopRifle$.getCurrentBloopVersion(BloopRifle.scala:192)
        at scala.build.bloop.BloopServer$.ensureBloopRunning(BloopServer.scala:85)
        at scala.build.bloop.BloopServer$.bsp(BloopServer.scala:153)
        at scala.build.bloop.BloopServer$.buildServer(BloopServer.scala:183)
        at scala.build.bloop.BloopServer$.withBuildServer(BloopServer.scala:248)
        at scala.build.Build$.build(Build.scala:422)
        at scala.build.Build$.build(Build.scala:449)
        at scala.cli.commands.Run$.run(Run.scala:94)
        at scala.cli.commands.Run$.run(Run.scala:25)
        at scala.cli.commands.Default.run(Default.scala:37)
        at scala.cli.commands.Default.run(Default.scala:9)
        at caseapp.core.app.CaseApp.main(CaseApp.scala:149)
        at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:116)
        at scala.cli.ScalaCliCommands.main(ScalaCliCommands.scala:89)
        at scala.cli.ScalaCli$.main0(ScalaCli.scala:148)
        at scala.cli.ScalaCli$.main(ScalaCli.scala:71)
        at scala.cli.ScalaCli.main(ScalaCli.scala)
```

**Comment by lwronski** [comment]
The same as in [#846](https://github.com/VirtusLab/scala-cli/issues/846#issuecomment-1123688757), 
if there is still the problem, you can re-open this issue with `scala-cli bloop output` result.
